spotify_ids = [
    {'name': 'Aleman', "id": '4QFG9KrGWEbr6hNA58CAqE'},
    {'name': 'Neto Peña', "id": '0U5RYP2HMdGv2GhicLhkOI'},
    {'name': 'Santa Fe', "id": '4tm8CEdm4pkQsEh4jIr9Yp'},
    {'name': 'Metrik Vader', "id": '47zSpyjndukb8rBLQSSU3T'},
    {'name': 'CKAN', "id": '1QhaqxeqF9sipS2gwbEKpu'},
    {'name': 'LNGSHT', "id": '2q9p1IXueDbcN4de5C9fI2'},
    {'name': 'AdanCruz', "id": '645xd9cHiiLqqehoLzLMDR'},
    {'name': 'Sr Marrano', "id": '4TGavohrECqpfWpLz6QhkG'},
    {'name': 'THRCru2', "id": '7qfeRXz0fErzIordtUUxYn'},
    {'name': 'EptosUno', "id": '3fo4UvMNzZUCFS90Roh5iK'},
    {'name': 'Mime 871', "id": '3lrhy6KigCHdcc0vOSTWoI'},
    {'name': 'Pato Machete', "id": '0Wvud7hEqI5zaI0o0iIkj2'},
    {'name': 'Control Machete', "id": '628gUkswCfCS1hIOOHmIpK'},
    {'name': 'Tino El Pinguino', "id": '3BbLQNj5OTxm4AZcwyREFF'},
    {'name': 'Boca Floja', "id": '2bj9MQez88g09q4NSr2xjS'},
    {'name': 'Akil Ammar', "id": '6lOqlvNZmpkmHNN1Ud4KXr'},
    {'name': 'West Gold', "id": '1gPiNBRjOB9XochAAFR3iM'},
    {'name': 'Robot', "id": '30CTTIqrcr82nS6B40j975'},
    {'name': 'Dharius', "id": '66RfYVdftqnuHRicyClgL0'},
    {'name': 'Hispana', "id": '7rTmbfDJtDCjoy8XK5Dsj5'},
    {'name': 'Cartel de Santa', "id": '07PdYoE4jVRF6Ut40GgVSP'},
    {'name': 'Aczino', "id": '4r1ZDYKzPt3iIjuq8LbT6X'},
    {'name': 'Coko', "id": '1txbs9MMkT4FszkaA96atm'},
    {'name': 'Charles Ans', "id": '5lYeiQxUTcGKVgAuTqbTeL'},
    {'name': 'Gera Mx', "id": '2hejA1Dkf8v8R0koF44FvW'},
    {'name': 'Yoss Bones', "id": '0SmgVe3giVHaJjGmIz8xA4'},
    {'name': 'Tabernario', "id": '2uG7vLSehD2quPeYSPkT73'},
    {'name': 'WK', "id": '7BQJLHBNVvz4O2JHmls4Ef'},
    {'name': 'Mike Diaz', "id": '5pR3pEU0bCMZhhAzag3DUz'},
    {'name': 'Lefty SM', "id": '6eXHRfK9Ad3IpMpSAqvcDf'},
    {'name': 'T-Killa', "id": '52QQ2BADyRwXsS8uqLu2Hl'},
    {'name': 'Faruz Feet', "id": '6tJRAxu0HwB2GI9GueEj4l'},
    {'name': 'Spvce Problems', "id": '0cyFixcJhYGoDQvgFOE2jq'},
    {'name': 'Reno 871', "id": '50nNZIMfSVOSOoZNPfgFCU'},
    {'name': 'Big Metra', "id": '5J5DLfdC5YmPjVk8ljdOqU'},
    {'name': 'Achepe', "id": '1b170j0PpkgYWGHMPRsNEM'},
    {'name': 'Santa RM', "id": '30BSBWLKnYJION1lCPugXc'},
    {'name': 'Fntxy', "id": '7I85Ma5xjAo6nlvqOCIiWx'},
    {'name': 'Yoga Fire', "id": '3AgxRYe2kXEfsZyB07hqJF'},
    {'name': 'Anexo Leiruk', "id": '4H3ePoFDdsl36QwB96jZzg'},
    {'name': 'Millonario', "id": '2N2aJ1SXQxMkhHD8C6fhYD'},
    {'name': 'Tren Lokote', "id": '6DjBv6gyR1HLsvwGUOD5V9'},
    {'name': 'El Pinche Mara', "id": '3L7OHIT4kfdcDSnnGM0TKN'},
    {'name': 'Geassasin', "id": '4V2V4PaSblStayYVWTGDbZ'},
    {'name': 'Logan Hate', "id": '3duZndoIzAXtBJj8op4Abx'},
    {'name': 'Dracks', "id": '1zbQgvftfbVN7pPyNuR2U0'},
    {'name': 'Phyz Eye', "id": '1NsRsBdRV7uWMw0SYaHo01'},
    {'name': 'Zaque', "id": '4WQmw3fIx9F7iPKL5v8SCN'},
    {'name': 'Muthahupa', "id": '5i0eAAl4YhI6TmPodtseGi'},
    {'name': 'Teeam Revolver', "id": '5MRMYpdAWZawm3ivBeWvdK'},
    {'name': 'Tiro Loko', "id": '4Y5HJP3oFOJ8UVBXHYWBgx'},
    {'name': 'Simspon ahuevo', "id": '6viZnVSHavFUcW0blu6Mvw'},
    {'name': 'Go Golden Junk', "id": '2tU377oBzcCBbRNeVve8FC'},
    {'name': 'Primero company', "id": '6pu8qjuOYZRBYc1hiHEVL5'},
    {'name': 'Tanke one', "id": '6CJ0EnASyencrooPZNBpaB'},
    {'name': 'Gino', "id": '3BRcyV18jhoYQCCk0PJvrw'},
    {'name': 'Montebel', "id": '3n3xqTWiJ5cThzS3UsDQUV'},
    {'name': 'Proof', "id": '2Gcx4c9rFAAloAYV2cMGUd'},
    {'name': 'Hadrian', "id": '2F9icYS5KP4Td9nbxIjo9q'},
    {'name': 'El pinche brujo', "id": '1LjUlFOtTxcvWZQldBMSOW'},
    {'name': 'Bull Montana', "id": '2OprAdrzD4U2JTrL2XGvkL'},
    {'name': 'Tonnie Rico', "id": '4FnLpt7y15mESBAhQMAoad'},
    {'name': 'Dasket Rapley', "id": '3pW4tw2BArwIClCWHjJWVF'},
    {'name': 'Little el Crack', "id": '20kZ1fvR4TfMUsyXfOOnAm'},
    {'name': 'Leazzy', "id": '4iPx95BzuqFwzfmIMPBC1p'},
    {'name': 'Rabia Rivera', "id": '1mKlMW38n3dOmsOIfaOaOU'},
    {'name': 'Sociedad Cafe', "id": '7FJZ5oy5kdpkqWYL2RGvRR'},
    {'name': 'Turek Hem', "id": '5HSROvpnFBzRENwjZ30RNx'},
    {'name': 'Jay Romero', "id": '4VECwDIJ0DYczPqCyP85kQ'},
    {'name': 'Buffon', "id": '7CvKsTEWv1BS3LydN8HgG6'},
    {'name': 'Remik', "id": '4Hzj6dfl1y5x5TzCSsvLB6'},
    {'name': 'Toser One', "id": '1oHPSeQJBwNmpq0J52Wjn1'},
    {'name': 'Mc Davo', "id": '3TGeuw7OmACouH5JAKkX7I'},
    {'name': 'Neto Reyno', "id": '7sgnuH8OwU32WbGLZwD03q'},
    {'name': 'Snow tha product', "id": '3p3jPcp8b7WL9XYj4xlsWj'},
    {'name': 'Ximbo', "id": '0RjHsbbdfnI3okpxdZ2JOV'},
    {'name': 'Vikcy MC', "id": '2sF3CgV1tKubYGTUSKPenC'},
    {'name': 'Zimple', "id": '0l1OSQn6GtjfEE1Cb8LE1t'},
    {'name': 'Zxmyr', "id": '7IUaYyqcGB3aU2Tm4s5JY8'},
    {'name': 'Lenin Pena', "id": '3hWsyFI2fjSLqdHukSWzev'},
    {'name': 'Zmoky', "id": '3yxAI1UvJFajyxQ1eLf8gO'},
    {'name': 'Guero Sosa', "id": '4QYW33jqI9hiFLgJBPDvwU'},
    {'name': 'Maythugs', "id": '50rhEb0qCmiMkWEb3eN0rH'},
    {'name': 'Lirika Inverza', "id": '214wdmDstodTL0SEEPDyxb'},
    {'name': 'Bizor', "id": '7F6fxMv0tz2Clj8H02Y2k7'},
    {'name': 'Caballeros del plan g', "id": '568lw0anJJJnjTXII3gHaf'},
    {'name': 'Don Aereo', "id": '2EkFEL5IvD2W8hpwbjS9yv'},
    {'name': 'Kosmer', "id": '2Ey4tRJ1hbrsMUn8GjhRn2'},
    {'name': 'Doctor Destino', "id": '5urer15JPbCELf17LVia7w'},
    {'name': 'Danger Ak', "id": '23TYM4mYLQjyJLr4x89MjH'},
    {'name': 'Cozy Cuz', "id": '3ScIigEm9KZUrUQtXzBmKJ'},
    {'name': 'Maniako', "id": '4XVWGb0bUVdiBhmWbSKSF3'},
    {'name': 'Kstro MGA', "id": '2cf3USXga99bsWQpBIcOl4'},
    {'name': 'Cesaranderan', "id": '3g3SX7D8ul0DxrOKlvjrKc'},
    {'name': 'Perro ZW', "id": '7CPuRgoqujB5wHULxqiIqv'},
    {'name': 'Manicomio Plan', "id": '4MU4o7Q9PEHnzuf1Kw5IBM'},
    {'name': 'Nedman Guerrero', "id": '216EDkKlBGRZUxVVhUwDll'},
    {'name': 'Rhomer', "id": '63YbwVzLF4i842NInZvY7J'},
    {'name': 'Kidd M', "id": '6hPRzsa6sYFIya5wOnzhzl'},
    {'name': 'Mc Luka', "id": '2HpeQd3eecBJ1cPR7SLcrP'},
    {'name': 'Skool 77', "id": '1XrrYgyQChyeEcHCG6AByX'},
    {'name': 'Fermin IV', "id": '74OPWhLPyLylAzgqcJlNMm'},
    {'name': 'Gogo Ras', "id": '0fCRMqA18mcwhcf5Rng0VF'},
    {'name': 'Dee', "id": '1jVhcHIGJuk16eqY1Mdtuk'},
    {'name': 'Industria City', "id": '4r0vcc9R6J1ovqC8282rX3'},
    {'name': 'Aguila Sativa', "id": '7CrI6hfM0LP4jQkaTzdHbz'},
    {'name': 'Masta Quba', "id": '6huE8Sh7scgoA8rj2vCuwZ'},
    {'name': 'Audry Funk', "id": '7eWbFrseRms5D5quwPDkm2'},
    {'name': 'Balliner', "id": '35BPWrbRCzHa7yWWvCi8BI'},
    {'name': 'Escuela Sinica', "id": '1jmpTEpfmOKFd90iLzjVeY'},
    {'name': 'Mare Advertencia Lirika', "id": '3QVB7ctBlqEFuQZeMDt6Qh'},
    {'name': 'Bobi Bozman', "id": '3N9ZhpiDCKh8UDpqf597SC'},
    {'name': 'Fume 871', "id": '4A0zvhdGzPzwgotxI5O3ci'},
    {'name': 'Drvgs', "id": '5VF9y2sGTphTF7jmXdplFu'},
    {'name': 'Limbo Lowfi', "id": '4EQWL5UyTdKnVQeIERcnpr'},
    {'name': 'Doble P Ache Ene', "id": '5yh17UV0XSFV1lzzFC39XR'},
    {'name': 'Twisted Minded', "id": '38nJKLU7rqAL9L2sJDniUH'},
    {'name': 'Brez', "id": '2jJmTEMkGQfH3BxoG3MQvF'},
    {'name': 'Akwid', "id": '3mYFuz6iY7D9X78rOXg5CG'},
    {'name': 'Carlos Cartoon', "id": '36FicGasyvKfn6whxEKdIS'},
    {'name': 'Eric El Niño', "id": '1PykidvCp6SM4KLJXDeprl'},
    {'name': 'Yak MAg', "id": '60IqCN3nOzZ13yd8dQy9cC'},
    {'name': 'Bruno Grasso', "id": '4fNQqyvcM71IyF2EitEtCj'},
    {'name': 'Rapozt Mortem', "id": '1KHXqOQxGsx47nQ3VsYCoy'},
    {'name': 'Justinani', "id": '6daEHaxdKjnIGxdpeVRVMf'},
    {'name': 'Malva', "id": '1fKmFe01L78vPmmiJ10LAs'},
    {'name': 'Menuda Coincidencia', "id": '6qmixZxMYL2jroxAqPQvRe'},
    {'name': 'La Banda Baston', "id": '3vV4Tf1iC8vEP9fLOLGUfP'},
    {'name': 'Spia 104', "id": '49Q2I0njyI8l2nxCgXoGQ8'},
    {'name': 'Jauría Santa', "id": '662f8mEv1eRLXE9DzBy4vV'},
    {'name': 'Solitario Mondragón', "id": '4KXpp5lz2MakNFcTszi2B9'},
    {'name': 'Bipo Montana', "id": '6JG2QQcaQBzinELNvu9PRk'},
    {'name': 'Caporal', "id": '0lnkz75zUi8LVZeY8qd9tI'},
    {'name': 'La Santa Grifa', "id": '1oH2B8tcHn4Gpl2bmmyd4A'},
    {'name': 'Playa Matafokas', "id": '2xNpzwTQFG6D04SSTb32R1'},
    {'name': 'Stilo',"id": '6nyqrmf9qc4W94YKtsPel9'},
    {'name': 'IQlover', "id": '4f3gfMiBebyuTylgG4hHbq'},
    {'name': 'Poofer', "id": '6KH83UCF9zwNaBi4IIJnjE'},
    {'name': 'Jony Beltran', "id":'7nN4ORhj5Mi3tgU9IwQrFv'},
    {'name': 'Sipo one', "id": '76V5aARZFI750zk1BglDV2'},
    {'name': 'T Killa', "id": '52QQ2BADyRwXsS8uqLu2Hl'},
    {'name': 'Kafe con leshe', "id": '4UEgTTHyAS3pq9s4I7nhZj'},
    {'name': 'Seyer black', "id": '0ajXUlyQnejinmO6xvBXtG'},
    {'name': 'Jezzy P', "id": '2hRGPSlRUReuHtM0Cx0R7W'},
    {'name': 'Richard Aumada', "id": '4oR06FdpsOJTcTnOkSzUsC'},
    {'name': 'Kinto Sol', "id": '0nOyxRsVicKeiBbB6zdIMu'},
    {'name': 'Solo Cadaver', "id": '2pOyR8sdYfEmd4VIyeLDUy'},
    {'name': 'Samantha Barron', "id": '0zfvfy9XlborSqXNRhi8Bk'},
    {'name': 'La Crista', "id": '3yDz5xFKNHH0dE309ZN07K'},
    {'name': 'Prymanena', "id": '3h0yqSdhPYKuC27VkPyYVh'},
    {'name': 'Ayaari Nocedal', "id": '5YEJGu6UlupM9I1E3T92rb'},
    {'name': 'Little Smoking', "id": '5mFSaUUW9ZwqpWN39fmbuZ'},
    {'name': 'Dely Underrap', "id": '1jSge7y9Iuz9gd878P1MpH'},
    {'name': 'Barbarela', "id": '2pFRwJDkZ3pvmzufOh2mc1'},
    {'name': 'Elie tigre', "id": '6tM7AHGyfVc57FK5hZlEd1'},
    {'name': 'Ogarita', "id": '7F1M9d3MFyaMI7exRlfWsu'},
    {'name': 'Under side', "id": '2NtN73hhhgFt2NmbBOlFz1'},
    {'name': 'Skilla OH', "id": '2pDnTVieeXwx8R9HbyAjhP'},
    {'name': 'Astrid Cruz', "id": '1WhuV4MAbMhWKjYXojKN8i'},
    {'name': 'Lady Yeska', "id": '5wbGMxTkF76IVFgDjchC0J'},
    {'name': 'miss ganjah', "id": '59DTprYmt2pwawfesGtjjH'},
    {'name': 'La gallo 320', "id": '3vMfBXxAZ9iG2u0VjNZ0IA'},
    {'name': 'Nanis weed', "id": '3E53XnrcqQ3FS7pxn20561'},
    {'name': 'Seyer black art gang', "id": '0ajXUlyQnejinmO6xvBXtG'},
    {'name': 'Bremont 420', "id": '0Pm1HMMO0w5Suw6JY9zSlm'},
    {'name': 'Dr destino', "id": '5urer15JPbCELf17LVia7w'},
    {'name': 'Dilema', "id": '3eCEorgAoZkvnAQLdy4x38'},
    {'name': 'Brez', "id": '2jJmTEMkGQfH3BxoG3MQvF'},
    {'name': 'Netilico', "id": '6olHsU1QdB0I5IBgVimUeU'},
    {'name': 'Tornillo', "id": '5OGraDcSkO4oTWthkm77WL'},
    {'name': 'Fiw', "id": '5rQxUSIyxeFcOv6XY8cGcg'},
    {'name': 'King Zoo', "id": '171953d8wJbRvl2f36uLDd'},
    {'name': 'Elote el barbaro', "id": '0yWcBatdQPfGvY4XEGeD6m'},
    {'name': 'Sinful el pecador', "id": '0CtBJEWIKkU8CzxJCBLmSi'},
    {'name': 'Chato 473', "id": '7zvcqoLiInqmSmPzX0gwfp'},
    {'name': 'Silar Kilos de estilo', "id": '0EuMnBFVFmyIFFgpiwbvj6'},
    {'name': 'Dyablo', "id": '7eU5CvFPPiqSqnKiNmZNy7'},
    {'name': 'Don kalavera', "id": '2nJOVl8u7PntefIs1Uwb4z'},
    {'name': 'Ñengo el quetzal', "id": '6M7bd1arTLm5FJnNFYKzb6'},
    {'name': 'Adan Zapata', "id": '1NGy8h3j8jFQvFv6cniUnl'},
    {'name': 'Lil wacho', "id": '5LSBA1VYe9Vvxute4ZCaZQ'},
    {'name': 'Sid MSC', "id": '60ltkiwaQfISsFpwwktCcb'},
    # {'name': 'Rich Vagos', "id": '1FCItwxfRieMGhR0eRxotU'},
    {'name': 'Jay Rick', "id": '0U8dIwzBn17JkhYxmznp6T'},
    {'name': 'Sandro Malandro', "id": '40FmJcZFhzbd6P9w4eXqgS'},
    {'name': 'Illegalez', "id": '1Fhcsda9LHOapGEZpOoAEj'},
    {'name': 'High Life', "id": '0VR2TEeHfqMZugZNANP1Dq'},
    {'name': 'Mr Pimp music', "id": '5zdoqaDKWhHtlFhoqfEn9N'},
    {'name': 'Maquina de fuego', "id": '0cCaNgZOOoHOFP5z7NYXcJ'},
    {'name': 'hombre Verso', "id": '1eNa31nlPvphoLmNwUrIhM'},
    {'name': 'Pakal', "id": '5ik5HDJQ996z6t41IBx6wu'},
    {'name': 'Alan SDR', "id": '4WHwVAuDtEVKIREviMhYOB'},
    {'name': 'Bruno Grasso', "id": '4fNQqyvcM71IyF2EitEtCj'},
    {'name': 'Cristy Loza', "id": '3Fz6oCeasrR52Sv7NJfpml'},
    {'name': 'Hione', "id": '0F3owIAAiwFiIzGP2YU6mg'},
]

youtube_ids = [
    {'name': 'Aleman', "id": 'UC9qH_PzG3TpfJpsRt9VfKcA'},
    {'name': 'Neto Peña', "id": 'UCrq2ArYU6XzMg_uAVPHCE3Q'},
    {'name': 'Santa Fe Klan', "id": 'UC4Ge3cqrdyOszmnJTcMICcg'},
    {'name': 'Metrik Vader', "id": 'UCOmtNKVF6BM8uNDbJR6D4LQ'},
    {'name': 'CKAN', "id": 'UCkD89TEFWsTZluY6tk84yqg'},
    {'name': 'LNGSHT', "id": 'UCwjXCWlTgAhfBlqttfFZ5rw'},
    {'name': 'AdanCruz', "id": 'UCsNud7A3Vz8X8Pqfw2L2wKg'},
    {'name': 'Sr Marrano', "id": 'UC1jqOSFKURb0QR9yErkBHlQ'},
    {'name': 'THRCru2', "id": 'UCXCiZmPpHnrAQ1mcfKQYm2A'},
    {'name': 'EptosUno', "id": 'UCsjwZJsy9IiykfPbZmYvp1A'},
    {'name': 'Mime 871', "id": 'UCcOlDiuXhTuNZlAZOmm21tA'},
    {'name': 'Pato Machete', "id": 'UCNVcXV-xZsnHjVxYSMEZROQ'},
    {'name': 'Control Machete', "id": 'UC9IzX1jMwTETgdV4WIIEvmQ'},
    {'name': 'Tino El Pinguino', "id": 'UCvkIHNuCuQs-JWF12f9TFvA	'},
    {'name': 'Boca Floja', "id": 'UCACalOr4wnNpTWw9Yyet4Tw'},
    {'name': 'Akil Ammar', "id": 'UCmNYsUc6ce4rH-GRFblKbCA'},
    {'name': 'West Gold', "id": 'UCvWNSFSHsGhaVXbJI_W3cdw'},
    {'name': 'Robot', "id": 'UCliRD7DSeqcuzudajJdWaLg'},
    {'name': 'king zoo', "id": 'UCl7BaSud7ML0WNowcsBFQ8w'},
    {'name': 'Dharius', "id": 'UCRWeaLWbhoHuHNjxLgG4asQ'},
    {'name': 'Hispana', "id": 'UC41ykKNl4Kakh6ISHp0KpVg'},
    {'name': 'Cartel de Santa', "id": 'UCunw-c0EKIX5LpPo8GpA2Aw'},
    {'name': 'Aczino', "id": 'UCGbyLk1twkkSSCFFMP1AZ9A'},
    {'name': 'Coko', "id": 'UC_qoGP7DFmu4JPLnF93tafQ'},
    {'name': 'Charles Ans', "id": 'UCVg8JuO9t0ZAmzPcd7C6AIQ'},
    {'name': 'Gera Mx', "id": 'UCwEJBGLB1knx2pYESEvWDWg'},
    {'name': 'Yoss Bones', "id": 'UCeQMZ68wcb97NCCKiI2KxnQ'},
    {'name': 'Tabernario', "id": 'UCXrtY_gHYMsPymMri6jRcsA'},
    {'name': 'WK', "id": 'UCLDG3G9RkdwDhrqxECJcTGQ'},
    {'name': 'Mike Diaz', "id": 'UCUg3gPjQk3MqMd3jKRbt4pA'},
    {'name': 'Lefty SM', "id": 'UCQFmPWnstWJ5LMwRmsK34Vg'},
    {'name': 'T-Killa', "id": 'UC9o3zPDOe3gLomzwdKXFnog'},
    {'name': 'Faruz Feet', "id": 'UCyVy4S_1se6l-8u14eSMalg'},
    {'name': 'Spvce Problems', "id": 'UCiXdgdYslSIrz3PbC-7JiNg'},
    {'name': 'Reno 871', "id": 'UCzinKCm3KrqoAiJGgToNzpw'},
    {'name': 'Big Metra', "id": 'UCW_8p4Mi94UQg7vQPRwrGKA'},
    {'name': 'Achepe', "id": 'UCfTcSqx_3gSHtThZDg73Low'},
    {'name': 'Santa RM', "id": 'UCwiiACQ5jBDLF1kbrdzVaWA'},
    {'name': 'Fntxy', "id": 'UCd3rXLucYUfOe4I0cPo6GqQ'},
    {'name': 'Yoga Fire', "id": 'UCKW16mhYlN53-pfwWt3XJvQ'},
    {'name': 'Anexo Leiruk', "id": 'UCdV9NxSCAhc1jUPBlrwhOdQ'},
    {'name': 'Millonario', "id": 'UC35vyo1h2K_jLNi8oFtC9QA'},
    {'name': 'Tren Lokote', "id": 'UCP5-WPv_aHthE2jTZoLHbmg'},
    {'name': 'El Pinche Mara', "id": 'UCCj3pPQEgk_AMvWi5_1RYHw'},
    {'name': 'Geassasin', "id": 'UCC8gEoiVZcB24IIOBQfmpyQ'},
    {'name': 'Logan Hate', "id": 'UC7prW0Eq54-nv1d9j99l8qQ'},
    {'name': 'Dracks', "id": 'UCwMgQFIKrh6xyszppvRHhZw'},
    {'name': 'Phyz Eye', "id": 'UCzPWzNmROkktq4YRFg2y0MQ'},
    {'name': 'Zaque', "id": 'UCXLJPF4RRLT4aoVJkXG80bg'},
    {'name': 'Muthahupa', "id": 'UCxHKmJE_c5IimjhQdksRYoA'},
    {'name': 'Teeam Revolver', "id": 'UCh0EgbExTBNiB31bjhfht_Q'},
    {'name': 'Tiro Loko', "id": 'UCjvALbPcnSIS1xRjSvB7WCg'},
    {'name': 'Simspon ahuevo', "id": 'UCC42KGg_brOsjfA8ABAN5xQ'},
    {'name': 'Go Golden Junk', "id": 'UCO0cFgu4mVmCmmg9coTJDlg'},
    {'name': 'Primero company', "id": 'UCn2GwyJIIFKcxINfpp5TmxQ'},
    {'name': 'Tanke one', "id": 'UCjqSpoNRtIoeZeDUjvDaGmg'},
    {'name': 'Gino', "id": 'UCJ0qtr3XpTk5v0_eDgeLqEQ'},
    {'name': 'Montebel', "id": 'UCPcnyvY1XIC57mUnJzZSx1Q'},
    {'name': 'Proof', "id": 'UCkXBIPhqndAH5vqgMJyIZeg'},
    {'name': 'Hadrian', "id": 'UCDN7z4dol0uUHf749gJrrvQ'},
    {'name': 'El pinche brujo', "id": 'UC8qBl25vUefhuklVQLx7cJQ'},
    {'name': 'Bull Montana', "id": 'UCY0SVFoEwcsLfKs7LXUsXNQ'},
    {'name': 'Tonnie Rico', "id": 'UCFh6L1uNQj1n-T--ARecANA'},
    {'name': 'Dasket Rapley', "id": 'UC1M0jJqDr4eOYXQJ1ZvnV6g'},
    {'name': 'Little el Crack', "id": 'UCU2tjq7ZmZhIfwkdtikAW8Q'},
    {'name': 'Leazzy', "id": 'UCmcMLtd_OaX_-GG8GIUgqew'},
    {'name': 'Rabia Rivera', "id": 'UCFDrkf0_avZvZ9NJdPWwKkg'},
    {'name': 'Sociedad Cafe', "id": 'UCEHcjPXK3ghcIwZ2sflg5LA'},
    {'name': 'Turek Hem', "id": 'UCx7FMYdnthMR7FouYrfJ0fQ'},
    {'name': 'Jay Romero', "id": 'UCG_LojB0IUo8vi1xcyIJrXg'},
    # {'name': 'Buffon', "id": 'UCwfgnsnWfVi_kV54PmyVK_w'},
    {'name': 'Remik', "id": 'UC1hlr4QMZoNPEuxXOvsFhqA'},
    {'name': 'Toser One', "id": 'UCQf542MPMWUWq6l65rsV_Kw'},
    {'name': 'Under S"id"e', "id": 'UC65j313QwkFbx6fwGo4Oh5w'},
    {'name': 'Mc Davo', "id": 'UCCmXcYtA4T9wxc3vmbGFxRA'},
    {'name': 'Neto Reyno', "id": 'UCGo_5Z7bBN53zAXCXHGYYBg'},
    {'name': 'Snow tha product', "id": 'UCb934vQ6fg1JZQKvkCQ_j-Q'},
    {'name': 'Ximbo', "id": 'UCBcbw1KWVa6I30snV6Eovpg'},
    {'name': 'Vikcy MC', "id": 'UC1n9krq-c4QS54Ongn321zg'},
    {'name': 'Zimple', "id": 'UCGTvaChL1QKtfjyTGSAmTfQ'},
    {'name': 'Zxmyr', "id": 'UCZ4NWZseJmo7QXlZKkib_iA'},
    {'name': 'Lenin Pena', "id": 'UCOwUHROBsFWiMjO5n_TvxpQ'},
    {'name': 'Smoky', "id": 'UCc4Ynwucqf4PRdFSP2zhUFA'},
    {'name': 'Guero Sosa', "id": 'UCGH05t7k8We4RtCP78ahxZg'},
    {'name': 'Maythugs', "id": 'UCPgrJbHM_xj_VTlkGgazm_Q'},
    {'name': 'Lirika Inverza', "id": 'UC5ZfH3CHGSiwfYg0u2pCDZQ'},
    {'name': 'Bizor', "id": 'UCHPiQ86JdN3FILNDwR_mxkw'},
    {'name': 'Caballeros del plan g', "id": 'UCUFzwKTcTQkEyMYdND7NNfQ'},
    {'name': 'Don Aereo', "id": 'UCaEZ1OAjebcZOnVcNhBZrZQ'},
    {'name': 'Kosmer', "id": 'UCFmQe7QD6vNG0761Vb-lTGg'},
    {'name': 'Doctor Destino', "id": 'UCGXC-OtIZ7PHOHBKZTE4mIw'},
    {'name': 'Danger Ak', "id": 'UCRma-nTsuq_4w9KkCJJYSig'},
    {'name': 'Cozy Cuz', "id": 'UChyHg_8LNYa3yydCNcfp5ZQ'},
    {'name': 'Maniako', "id": 'UCBAabiLiKLsB6uhKuTdRa0g'},
    {'name': 'Kstro MGA', "id": 'UCxtFOI2k-NwJpy8Qv4dDH6w'},
    {'name': 'Cesaranderan', "id": 'UCb0kJUplVTwAs20FvSAX11A'},
    {'name': 'Perro ZW', "id": 'UC9PJj_Wj2XK_6Cd8YwAVbnQ'},
    # {'name': 'Manicomio Plan', "id": ''},
    {'name': 'Nedman Guerrero', "id": 'UCQ51rJk17ryq0bQOqxwC3_w'},
    {'name': 'Rhomer', "id": 'UC8yPdJQF5GMbf7phZixqc7Q'},
    {'name': 'K"id"d M', "id": 'UCSBtOiP93gtOKBUxzH82cdA'},
    {'name': 'Mc Luka', "id": 'UCtA_PL0vHPlJdJWG1U5wrtA'},
    {'name': 'Skool 77', "id": 'UCTpJ5FCcMwtlKaGPM3KmtXg'},
    {'name': 'Fermin IV', "id": 'UCGM3UlzIWwkQipcweaNaiYA'},
    {'name': 'Gogo Ras', "id": 'UCl8RpiWbO_usXsUVcCt65Tw'},
    {'name': 'Dee', "id": 'UCEGMF-OtAZZFZmKNovSIdGg'},
    {'name': 'Industria City', "id": 'UC_IjyhW-bNkMyTl67trAPHg'},
    {'name': 'Gooti Records', "id": 'UCtMv-a8SY-rO7KBg9hgaWMQ'},
    {'name': 'Masta Quba', "id": 'UCT_pGv1vC2W9FxSF4d1ARYw'},
    {'name': 'Audry Funk', "id": 'UCP0bHEgMjKkbvHLJPO3Pgvg'},
    {'name': 'Ogarita', "id": 'UC9MfCD9NvAuUcc3-SdtnSZQ'},
    {'name': 'Ballin', "id": 'UC-Un35k-4kAVt_ZayveoHDQ'},
    {'name': 'Escuela Sinica', "id": 'UC8QPOUi9Al6vjtzJUTU4AqQ'},
    {'name': 'Mare Advertencia Lirika', "id": 'UCoeKgIyB_k2HU_Wd0nyCcAA'},
    {'name': 'Bobi Bozman', "id": 'UCwxsBHYjR-26lqb4rumBQfg'},
    {'name': 'Fume 871', "id": 'UCIsL3HP_ub3RJL357hge9vA'},
    {'name': 'Drvgs', "id": 'UCbqWnvHkYPlw6QhMIun8p8w'},
    {'name': 'Limbo Lowfi', "id": 'UCV0NSwIfpiI8UM9oclyAT7A'},
    {'name': 'Doble P Ache Ene', "id": 'UCKTOXzyK8A949bkGLL_s-yg'},
    {'name': 'Rhinox', "id": 'UCCgru39nvvT4HagCeAzF7cg'},
    # {'name': 'Brez', "id": ''},
    # {'name': 'Akw"id"', "id": ''},
    {'name': 'Carlos Cartoon', "id": 'UCHmPzq-rblI2ePxWGkiqr_Q'},
    {'name': 'Eric El Niño', "id": 'UCYK6niNrGz_a0r95tjalt-w'},
    {'name': 'Yak MAg', "id": 'UC3HDL48GvKcsItnMWMmAf3Q'},
    # {'name': 'Bruno Grasso', "id": 'UCasmKZTUJV2Pj5p6YmHNLrw'},
    {'name': 'Rapozt Mortem', "id": 'UCtzRQlSROUqceyhsyt-yZRw'},
    {'name': 'Justinani', "id": 'UCWx6wb45qiquiSOVo9n_jFQ'},
    # {'name': 'Malva', "id": ''},
    {'name': 'Menuda Coincidencia', "id": 'UCk6kHu64yemOY3rhoYNwndw'},
    {'name': 'La Banda Baston', "id": 'UCHNAy303XjuHFutICph-xyQ'},
    # {'name': 'Spia 104', "id": ''},
    {'name': 'Jauría Santa', "id": 'UCAoiYfsSUrfKzNqmYSe3sbA'},
    {'name': 'Solitario Mondragón', "id": 'UC6aHJnbrit1oPsyJl_S1zew'},
    {'name': 'Bipo Montana', "id": 'UCozby0zIOZuLVVRKg9Yk7KQ'},
    {'name': 'Caporal', "id": 'UCfcpt5PTNAACwcnJUbrj6hA'},
    {'name': 'La Santa Grifa', "id": 'UCOHiOs8GrK0Nz8p_fbNnADQ'},
    {'name': 'Playa Matafokas', "id": 'UCOmtNKVF6BM8uNDbJR6D4LQ'},
    {'name': 'Stilo',"id": 'UCaeB4QDRK-lI2Afif8j3oUg'},
    {'name': 'IQlover', "id": 'UCl7BaSud7ML0WNowcsBFQ8w'},
    {'name': 'Poofer', "id": 'UC1xVjSVgk5YXpAK8db1JyWA'},
    {'name': 'Jony Beltran', "id":'UCvMG8jdxTfTfZTMOtN7BG6g'},
    {'name': 'Sipo one', "id": 'UC_DHJfesxbCEmg9b_AJRNcA'},
    {'name': 'T Killa', "id": 'UC9o3zPDOe3gLomzwdKXFnog'},
    {'name': 'Kafe con leshe', "id": 'UCMZDsInSio5ELUZaiyWmTLg'},
    # {'name': 'Seyer black', "id": ''},
    {'name': 'Jezzy P', "id": 'UC99BrDRiPkPURkDkhJPxgZA'},
    {'name': 'Richard Aumada', "id": 'UCDlgDrcAcfDgA7EOfwi_L4w'},
    {'name': 'Kinto Sol', "id": 'UC89T-BR3lxaq89mqx6qPGfA'},
    {'name': 'Fosa Comun', "id": 'UCM67oH4uzA7kWxh7Pf4G37w'},
    {'name': 'skilla holiday', "id": 'UCjGczgZ8eeUj8zEWhcrSnyw'},
    {'name': 'dabeat ramirez', "id": 'UCtpFK8OKRazxx8f46ZeGPNQ'},
    {'name': 'seyer black', "id": 'UCaMofUsHxRr3AjN-WlLPUrQ'},
    {'name': 'solo cadaver', "id": 'UCaoaWmbKyrzkjNpPKO-elhQ'},
    {'name': 'fiw', "id": 'UCWPUInlefYIPxfD4FuKfNfA'},
    {'name': 'la gallo', "id": 'UCk-iNn1I0SzbI6OuCNMxtrg'},
    {'name': 'barbarela', "id": 'UCNPDNMpvHLh9UNWcTVj9Y5Q'},
    {'name': 'gisela gaxiola', "id": 'UCH6sYgwQ68hi9pFL-kZ6vZA'},
    {'name': 'samantha barron', "id": 'UC26ng48UilLq6eEpahHufmQ'},
    {'name': 'astrid cruz', "id": 'UC2gMOMJbxMeT0ncLGSvPLNQ'},
    {'name': 'lorena padme', "id": 'UC5WbdC53ULuI8lDeQZkLLfA'},
    {'name': 'neftys', "id": 'UCNBluHIJvLb41CZHm5UU0qg'},
    {'name': 'tu segunda madre', "id": 'UCZGrmyeQSq_0CZo8YKQAjog'},
    {'name': 'elie tigre', "id": 'UC70gIpZPu9EUqT4OypyYI-Q'},
    {'name': 'Yeimy Ochoa', "id": 'UCB4Ppj1MwBGI9Ef4UKqJ1wQ'},
    {'name': 'Ayaari nocedal', "id": 'UCMoW-JmJdy3th3Lj6MLgxZg'},
    {'name': 'Prima nena', "id": 'UCAk71VHs-2cwRBk8r61tbQA'},
    {'name': 'Nanis weed', "id": 'UCrwSa_k0p7N7vHrL-CIypkg'},
    {'name': 'Picky Ramirez', "id": 'UCRKNvroYfaEV580dwS8zGJQ'},
    {'name': 'Dely Underrap', "id": 'UCmc4PSq3005xCQxTh470Brg'},
    {'name': 'Jota ache', "id": 'UCJIAvcZzpi2b-1yphqbdRDw'},
    {'name': 'Hechura', "id": 'UCANIkUXgxwaKBqas2jTEoAg'},
    {'name': 'Abril Mancilla', "id": 'UC7a6heE-U0M9vMtKk_-4b8Q'},
    {'name': 'Miss Ganjah', "id": 'UCXp-STMrAEWPYnlvHEiC9qg'},
    {'name': 'Ana mc', "id": 'UC46IXCPX-vp0zlgiivNWfZA'},
    {'name': 'Ikal Killa', "id": 'UCn9h9dp04vghq2ECpjI8X3Q'},
    {'name': 'Little Smoking', "id": 'UCEJFz7QINlpcUoeYGUAvVDA'},
    {'name': 'La Gyal', "id": 'UCfIAcQ5pnHrBjsu4S0YJuCA'},
]