-- Aritmetrica: esquema + seed desde artist_ids.py
-- Sin tabla única de artista: spotify y youtube son independientes.
-- YouTube permite varios canales por nombre de artista; channel_id es único global.
-- Ejecutar en el VPS, por ejemplo:
--   mysql -h 127.0.0.1 -u USUARIO -p < sql/todo_aritmetrica.sql
-- Este script hace DROP de tablas al inicio.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE DATABASE IF NOT EXISTS `aritmetrica-stats`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `aritmetrica-stats`;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS pending_artist_submissions;
DROP TABLE IF EXISTS endpoint_counter;
DROP TABLE IF EXISTS youtube_artist_channels;
DROP TABLE IF EXISTS spotify_artists;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE spotify_artists (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  artist_name VARCHAR(255) NOT NULL,
  spotify_artist_id VARCHAR(32) NOT NULL,
  profile_url VARCHAR(512) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_spotify_artist_id (spotify_artist_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE youtube_artist_channels (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  artist_name VARCHAR(255) NOT NULL,
  youtube_channel_id VARCHAR(64) NOT NULL,
  channel_url VARCHAR(512) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_youtube_channel_id (youtube_channel_id),
  KEY idx_youtube_artist_name (artist_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE pending_artist_submissions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  artist_name VARCHAR(255) NOT NULL,
  source_url VARCHAR(2048) NOT NULL,
  status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  corrected_url VARCHAR(2048) DEFAULT NULL,
  platform ENUM('spotify', 'youtube') DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  reviewed_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_pending_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Contador: respuestas HTTP exitosas (< 400), excluir /admin en la app
CREATE TABLE endpoint_counter (
  endpoint_path VARCHAR(255) NOT NULL,
  success_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  last_success_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (endpoint_path)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Registros omitidos en seed por ID duplicado (primera aparición en artist_ids.py gana)
-- youtube id UCOmtNKVF6BM8uNDbJR6D4LQ: omitido 'Playa Matafokas', conservado 'Metrik Vader'
-- youtube id UCl7BaSud7ML0WNowcsBFQ8w: omitido 'IQlover', conservado 'king zoo'
-- youtube id UC9o3zPDOe3gLomzwdKXFnog: omitido 'T Killa', conservado 'T-Killa'

INSERT INTO spotify_artists (artist_name, spotify_artist_id, profile_url) VALUES
('Aleman', '4QFG9KrGWEbr6hNA58CAqE', 'https://open.spotify.com/artist/4QFG9KrGWEbr6hNA58CAqE'),
('Neto Peña', '0U5RYP2HMdGv2GhicLhkOI', 'https://open.spotify.com/artist/0U5RYP2HMdGv2GhicLhkOI'),
('Santa Fe', '4tm8CEdm4pkQsEh4jIr9Yp', 'https://open.spotify.com/artist/4tm8CEdm4pkQsEh4jIr9Yp'),
('Metrik Vader', '47zSpyjndukb8rBLQSSU3T', 'https://open.spotify.com/artist/47zSpyjndukb8rBLQSSU3T'),
('CKAN', '1QhaqxeqF9sipS2gwbEKpu', 'https://open.spotify.com/artist/1QhaqxeqF9sipS2gwbEKpu'),
('LNGSHT', '2q9p1IXueDbcN4de5C9fI2', 'https://open.spotify.com/artist/2q9p1IXueDbcN4de5C9fI2'),
('AdanCruz', '645xd9cHiiLqqehoLzLMDR', 'https://open.spotify.com/artist/645xd9cHiiLqqehoLzLMDR'),
('Sr Marrano', '4TGavohrECqpfWpLz6QhkG', 'https://open.spotify.com/artist/4TGavohrECqpfWpLz6QhkG'),
('THRCru2', '7qfeRXz0fErzIordtUUxYn', 'https://open.spotify.com/artist/7qfeRXz0fErzIordtUUxYn'),
('EptosUno', '3fo4UvMNzZUCFS90Roh5iK', 'https://open.spotify.com/artist/3fo4UvMNzZUCFS90Roh5iK'),
('Mime 871', '3lrhy6KigCHdcc0vOSTWoI', 'https://open.spotify.com/artist/3lrhy6KigCHdcc0vOSTWoI'),
('Pato Machete', '0Wvud7hEqI5zaI0o0iIkj2', 'https://open.spotify.com/artist/0Wvud7hEqI5zaI0o0iIkj2'),
('Control Machete', '628gUkswCfCS1hIOOHmIpK', 'https://open.spotify.com/artist/628gUkswCfCS1hIOOHmIpK'),
('Tino El Pinguino', '3BbLQNj5OTxm4AZcwyREFF', 'https://open.spotify.com/artist/3BbLQNj5OTxm4AZcwyREFF'),
('Boca Floja', '2bj9MQez88g09q4NSr2xjS', 'https://open.spotify.com/artist/2bj9MQez88g09q4NSr2xjS'),
('Akil Ammar', '6lOqlvNZmpkmHNN1Ud4KXr', 'https://open.spotify.com/artist/6lOqlvNZmpkmHNN1Ud4KXr'),
('West Gold', '1gPiNBRjOB9XochAAFR3iM', 'https://open.spotify.com/artist/1gPiNBRjOB9XochAAFR3iM'),
('Robot', '30CTTIqrcr82nS6B40j975', 'https://open.spotify.com/artist/30CTTIqrcr82nS6B40j975'),
('Dharius', '66RfYVdftqnuHRicyClgL0', 'https://open.spotify.com/artist/66RfYVdftqnuHRicyClgL0'),
('Hispana', '7rTmbfDJtDCjoy8XK5Dsj5', 'https://open.spotify.com/artist/7rTmbfDJtDCjoy8XK5Dsj5'),
('Cartel de Santa', '07PdYoE4jVRF6Ut40GgVSP', 'https://open.spotify.com/artist/07PdYoE4jVRF6Ut40GgVSP'),
('Aczino', '4r1ZDYKzPt3iIjuq8LbT6X', 'https://open.spotify.com/artist/4r1ZDYKzPt3iIjuq8LbT6X'),
('Coko', '1txbs9MMkT4FszkaA96atm', 'https://open.spotify.com/artist/1txbs9MMkT4FszkaA96atm'),
('Charles Ans', '5lYeiQxUTcGKVgAuTqbTeL', 'https://open.spotify.com/artist/5lYeiQxUTcGKVgAuTqbTeL'),
('Gera Mx', '2hejA1Dkf8v8R0koF44FvW', 'https://open.spotify.com/artist/2hejA1Dkf8v8R0koF44FvW'),
('Yoss Bones', '0SmgVe3giVHaJjGmIz8xA4', 'https://open.spotify.com/artist/0SmgVe3giVHaJjGmIz8xA4'),
('Tabernario', '2uG7vLSehD2quPeYSPkT73', 'https://open.spotify.com/artist/2uG7vLSehD2quPeYSPkT73'),
('WK', '7BQJLHBNVvz4O2JHmls4Ef', 'https://open.spotify.com/artist/7BQJLHBNVvz4O2JHmls4Ef'),
('Mike Diaz', '5pR3pEU0bCMZhhAzag3DUz', 'https://open.spotify.com/artist/5pR3pEU0bCMZhhAzag3DUz'),
('Lefty SM', '6eXHRfK9Ad3IpMpSAqvcDf', 'https://open.spotify.com/artist/6eXHRfK9Ad3IpMpSAqvcDf'),
('T-Killa', '52QQ2BADyRwXsS8uqLu2Hl', 'https://open.spotify.com/artist/52QQ2BADyRwXsS8uqLu2Hl'),
('Faruz Feet', '6tJRAxu0HwB2GI9GueEj4l', 'https://open.spotify.com/artist/6tJRAxu0HwB2GI9GueEj4l'),
('Spvce Problems', '0cyFixcJhYGoDQvgFOE2jq', 'https://open.spotify.com/artist/0cyFixcJhYGoDQvgFOE2jq'),
('Reno 871', '50nNZIMfSVOSOoZNPfgFCU', 'https://open.spotify.com/artist/50nNZIMfSVOSOoZNPfgFCU'),
('Big Metra', '5J5DLfdC5YmPjVk8ljdOqU', 'https://open.spotify.com/artist/5J5DLfdC5YmPjVk8ljdOqU'),
('Achepe', '1b170j0PpkgYWGHMPRsNEM', 'https://open.spotify.com/artist/1b170j0PpkgYWGHMPRsNEM'),
('Santa RM', '30BSBWLKnYJION1lCPugXc', 'https://open.spotify.com/artist/30BSBWLKnYJION1lCPugXc'),
('Fntxy', '7I85Ma5xjAo6nlvqOCIiWx', 'https://open.spotify.com/artist/7I85Ma5xjAo6nlvqOCIiWx'),
('Yoga Fire', '3AgxRYe2kXEfsZyB07hqJF', 'https://open.spotify.com/artist/3AgxRYe2kXEfsZyB07hqJF'),
('Anexo Leiruk', '4H3ePoFDdsl36QwB96jZzg', 'https://open.spotify.com/artist/4H3ePoFDdsl36QwB96jZzg'),
('Millonario', '2N2aJ1SXQxMkhHD8C6fhYD', 'https://open.spotify.com/artist/2N2aJ1SXQxMkhHD8C6fhYD'),
('Tren Lokote', '6DjBv6gyR1HLsvwGUOD5V9', 'https://open.spotify.com/artist/6DjBv6gyR1HLsvwGUOD5V9'),
('El Pinche Mara', '3L7OHIT4kfdcDSnnGM0TKN', 'https://open.spotify.com/artist/3L7OHIT4kfdcDSnnGM0TKN'),
('Geassasin', '4V2V4PaSblStayYVWTGDbZ', 'https://open.spotify.com/artist/4V2V4PaSblStayYVWTGDbZ'),
('Logan Hate', '3duZndoIzAXtBJj8op4Abx', 'https://open.spotify.com/artist/3duZndoIzAXtBJj8op4Abx'),
('Dracks', '1zbQgvftfbVN7pPyNuR2U0', 'https://open.spotify.com/artist/1zbQgvftfbVN7pPyNuR2U0'),
('Phyz Eye', '1NsRsBdRV7uWMw0SYaHo01', 'https://open.spotify.com/artist/1NsRsBdRV7uWMw0SYaHo01'),
('Zaque', '4WQmw3fIx9F7iPKL5v8SCN', 'https://open.spotify.com/artist/4WQmw3fIx9F7iPKL5v8SCN'),
('Muthahupa', '5i0eAAl4YhI6TmPodtseGi', 'https://open.spotify.com/artist/5i0eAAl4YhI6TmPodtseGi'),
('Teeam Revolver', '5MRMYpdAWZawm3ivBeWvdK', 'https://open.spotify.com/artist/5MRMYpdAWZawm3ivBeWvdK'),
('Tiro Loko', '4Y5HJP3oFOJ8UVBXHYWBgx', 'https://open.spotify.com/artist/4Y5HJP3oFOJ8UVBXHYWBgx'),
('Simspon ahuevo', '6viZnVSHavFUcW0blu6Mvw', 'https://open.spotify.com/artist/6viZnVSHavFUcW0blu6Mvw'),
('Go Golden Junk', '2tU377oBzcCBbRNeVve8FC', 'https://open.spotify.com/artist/2tU377oBzcCBbRNeVve8FC'),
('Primero company', '6pu8qjuOYZRBYc1hiHEVL5', 'https://open.spotify.com/artist/6pu8qjuOYZRBYc1hiHEVL5'),
('Tanke one', '6CJ0EnASyencrooPZNBpaB', 'https://open.spotify.com/artist/6CJ0EnASyencrooPZNBpaB'),
('Gino', '3BRcyV18jhoYQCCk0PJvrw', 'https://open.spotify.com/artist/3BRcyV18jhoYQCCk0PJvrw'),
('Montebel', '3n3xqTWiJ5cThzS3UsDQUV', 'https://open.spotify.com/artist/3n3xqTWiJ5cThzS3UsDQUV'),
('Proof', '2Gcx4c9rFAAloAYV2cMGUd', 'https://open.spotify.com/artist/2Gcx4c9rFAAloAYV2cMGUd'),
('Hadrian', '2F9icYS5KP4Td9nbxIjo9q', 'https://open.spotify.com/artist/2F9icYS5KP4Td9nbxIjo9q'),
('El pinche brujo', '1LjUlFOtTxcvWZQldBMSOW', 'https://open.spotify.com/artist/1LjUlFOtTxcvWZQldBMSOW'),
('Bull Montana', '2OprAdrzD4U2JTrL2XGvkL', 'https://open.spotify.com/artist/2OprAdrzD4U2JTrL2XGvkL'),
('Tonnie Rico', '4FnLpt7y15mESBAhQMAoad', 'https://open.spotify.com/artist/4FnLpt7y15mESBAhQMAoad'),
('Dasket Rapley', '3pW4tw2BArwIClCWHjJWVF', 'https://open.spotify.com/artist/3pW4tw2BArwIClCWHjJWVF'),
('Little el Crack', '20kZ1fvR4TfMUsyXfOOnAm', 'https://open.spotify.com/artist/20kZ1fvR4TfMUsyXfOOnAm'),
('Leazzy', '4iPx95BzuqFwzfmIMPBC1p', 'https://open.spotify.com/artist/4iPx95BzuqFwzfmIMPBC1p'),
('Rabia Rivera', '1mKlMW38n3dOmsOIfaOaOU', 'https://open.spotify.com/artist/1mKlMW38n3dOmsOIfaOaOU'),
('Sociedad Cafe', '7FJZ5oy5kdpkqWYL2RGvRR', 'https://open.spotify.com/artist/7FJZ5oy5kdpkqWYL2RGvRR'),
('Turek Hem', '5HSROvpnFBzRENwjZ30RNx', 'https://open.spotify.com/artist/5HSROvpnFBzRENwjZ30RNx'),
('Jay Romero', '4VECwDIJ0DYczPqCyP85kQ', 'https://open.spotify.com/artist/4VECwDIJ0DYczPqCyP85kQ'),
('Buffon', '7CvKsTEWv1BS3LydN8HgG6', 'https://open.spotify.com/artist/7CvKsTEWv1BS3LydN8HgG6'),
('Remik', '4Hzj6dfl1y5x5TzCSsvLB6', 'https://open.spotify.com/artist/4Hzj6dfl1y5x5TzCSsvLB6'),
('Toser One', '1oHPSeQJBwNmpq0J52Wjn1', 'https://open.spotify.com/artist/1oHPSeQJBwNmpq0J52Wjn1'),
('Mc Davo', '3TGeuw7OmACouH5JAKkX7I', 'https://open.spotify.com/artist/3TGeuw7OmACouH5JAKkX7I'),
('Neto Reyno', '7sgnuH8OwU32WbGLZwD03q', 'https://open.spotify.com/artist/7sgnuH8OwU32WbGLZwD03q'),
('Snow tha product', '3p3jPcp8b7WL9XYj4xlsWj', 'https://open.spotify.com/artist/3p3jPcp8b7WL9XYj4xlsWj'),
('Ximbo', '0RjHsbbdfnI3okpxdZ2JOV', 'https://open.spotify.com/artist/0RjHsbbdfnI3okpxdZ2JOV'),
('Vikcy MC', '2sF3CgV1tKubYGTUSKPenC', 'https://open.spotify.com/artist/2sF3CgV1tKubYGTUSKPenC'),
('Zimple', '0l1OSQn6GtjfEE1Cb8LE1t', 'https://open.spotify.com/artist/0l1OSQn6GtjfEE1Cb8LE1t'),
('Zxmyr', '7IUaYyqcGB3aU2Tm4s5JY8', 'https://open.spotify.com/artist/7IUaYyqcGB3aU2Tm4s5JY8'),
('Lenin Pena', '3hWsyFI2fjSLqdHukSWzev', 'https://open.spotify.com/artist/3hWsyFI2fjSLqdHukSWzev'),
('Zmoky', '3yxAI1UvJFajyxQ1eLf8gO', 'https://open.spotify.com/artist/3yxAI1UvJFajyxQ1eLf8gO'),
('Guero Sosa', '4QYW33jqI9hiFLgJBPDvwU', 'https://open.spotify.com/artist/4QYW33jqI9hiFLgJBPDvwU'),
('Maythugs', '50rhEb0qCmiMkWEb3eN0rH', 'https://open.spotify.com/artist/50rhEb0qCmiMkWEb3eN0rH'),
('Lirika Inverza', '214wdmDstodTL0SEEPDyxb', 'https://open.spotify.com/artist/214wdmDstodTL0SEEPDyxb'),
('Bizor', '7F6fxMv0tz2Clj8H02Y2k7', 'https://open.spotify.com/artist/7F6fxMv0tz2Clj8H02Y2k7'),
('Caballeros del plan g', '568lw0anJJJnjTXII3gHaf', 'https://open.spotify.com/artist/568lw0anJJJnjTXII3gHaf'),
('Don Aereo', '2EkFEL5IvD2W8hpwbjS9yv', 'https://open.spotify.com/artist/2EkFEL5IvD2W8hpwbjS9yv'),
('Kosmer', '2Ey4tRJ1hbrsMUn8GjhRn2', 'https://open.spotify.com/artist/2Ey4tRJ1hbrsMUn8GjhRn2'),
('Doctor Destino', '5urer15JPbCELf17LVia7w', 'https://open.spotify.com/artist/5urer15JPbCELf17LVia7w'),
('Danger Ak', '23TYM4mYLQjyJLr4x89MjH', 'https://open.spotify.com/artist/23TYM4mYLQjyJLr4x89MjH'),
('Cozy Cuz', '3ScIigEm9KZUrUQtXzBmKJ', 'https://open.spotify.com/artist/3ScIigEm9KZUrUQtXzBmKJ'),
('Maniako', '4XVWGb0bUVdiBhmWbSKSF3', 'https://open.spotify.com/artist/4XVWGb0bUVdiBhmWbSKSF3'),
('Kstro MGA', '2cf3USXga99bsWQpBIcOl4', 'https://open.spotify.com/artist/2cf3USXga99bsWQpBIcOl4'),
('Cesaranderan', '3g3SX7D8ul0DxrOKlvjrKc', 'https://open.spotify.com/artist/3g3SX7D8ul0DxrOKlvjrKc'),
('Perro ZW', '7CPuRgoqujB5wHULxqiIqv', 'https://open.spotify.com/artist/7CPuRgoqujB5wHULxqiIqv'),
('Manicomio Plan', '4MU4o7Q9PEHnzuf1Kw5IBM', 'https://open.spotify.com/artist/4MU4o7Q9PEHnzuf1Kw5IBM'),
('Nedman Guerrero', '216EDkKlBGRZUxVVhUwDll', 'https://open.spotify.com/artist/216EDkKlBGRZUxVVhUwDll'),
('Rhomer', '63YbwVzLF4i842NInZvY7J', 'https://open.spotify.com/artist/63YbwVzLF4i842NInZvY7J'),
('Kidd M', '6hPRzsa6sYFIya5wOnzhzl', 'https://open.spotify.com/artist/6hPRzsa6sYFIya5wOnzhzl'),
('Mc Luka', '2HpeQd3eecBJ1cPR7SLcrP', 'https://open.spotify.com/artist/2HpeQd3eecBJ1cPR7SLcrP'),
('Skool 77', '1XrrYgyQChyeEcHCG6AByX', 'https://open.spotify.com/artist/1XrrYgyQChyeEcHCG6AByX'),
('Fermin IV', '74OPWhLPyLylAzgqcJlNMm', 'https://open.spotify.com/artist/74OPWhLPyLylAzgqcJlNMm'),
('Gogo Ras', '0fCRMqA18mcwhcf5Rng0VF', 'https://open.spotify.com/artist/0fCRMqA18mcwhcf5Rng0VF'),
('Dee', '1jVhcHIGJuk16eqY1Mdtuk', 'https://open.spotify.com/artist/1jVhcHIGJuk16eqY1Mdtuk'),
('Industria City', '4r0vcc9R6J1ovqC8282rX3', 'https://open.spotify.com/artist/4r0vcc9R6J1ovqC8282rX3'),
('Aguila Sativa', '7CrI6hfM0LP4jQkaTzdHbz', 'https://open.spotify.com/artist/7CrI6hfM0LP4jQkaTzdHbz'),
('Masta Quba', '6huE8Sh7scgoA8rj2vCuwZ', 'https://open.spotify.com/artist/6huE8Sh7scgoA8rj2vCuwZ'),
('Audry Funk', '7eWbFrseRms5D5quwPDkm2', 'https://open.spotify.com/artist/7eWbFrseRms5D5quwPDkm2'),
('Balliner', '35BPWrbRCzHa7yWWvCi8BI', 'https://open.spotify.com/artist/35BPWrbRCzHa7yWWvCi8BI'),
('Escuela Sinica', '1jmpTEpfmOKFd90iLzjVeY', 'https://open.spotify.com/artist/1jmpTEpfmOKFd90iLzjVeY'),
('Mare Advertencia Lirika', '3QVB7ctBlqEFuQZeMDt6Qh', 'https://open.spotify.com/artist/3QVB7ctBlqEFuQZeMDt6Qh'),
('Bobi Bozman', '3N9ZhpiDCKh8UDpqf597SC', 'https://open.spotify.com/artist/3N9ZhpiDCKh8UDpqf597SC'),
('Fume 871', '4A0zvhdGzPzwgotxI5O3ci', 'https://open.spotify.com/artist/4A0zvhdGzPzwgotxI5O3ci'),
('Drvgs', '5VF9y2sGTphTF7jmXdplFu', 'https://open.spotify.com/artist/5VF9y2sGTphTF7jmXdplFu'),
('Limbo Lowfi', '4EQWL5UyTdKnVQeIERcnpr', 'https://open.spotify.com/artist/4EQWL5UyTdKnVQeIERcnpr'),
('Doble P Ache Ene', '5yh17UV0XSFV1lzzFC39XR', 'https://open.spotify.com/artist/5yh17UV0XSFV1lzzFC39XR'),
('Twisted Minded', '38nJKLU7rqAL9L2sJDniUH', 'https://open.spotify.com/artist/38nJKLU7rqAL9L2sJDniUH'),
('Brez', '2jJmTEMkGQfH3BxoG3MQvF', 'https://open.spotify.com/artist/2jJmTEMkGQfH3BxoG3MQvF'),
('Akwid', '3mYFuz6iY7D9X78rOXg5CG', 'https://open.spotify.com/artist/3mYFuz6iY7D9X78rOXg5CG'),
('Carlos Cartoon', '36FicGasyvKfn6whxEKdIS', 'https://open.spotify.com/artist/36FicGasyvKfn6whxEKdIS');

INSERT INTO spotify_artists (artist_name, spotify_artist_id, profile_url) VALUES
('Eric El Niño', '1PykidvCp6SM4KLJXDeprl', 'https://open.spotify.com/artist/1PykidvCp6SM4KLJXDeprl'),
('Yak MAg', '60IqCN3nOzZ13yd8dQy9cC', 'https://open.spotify.com/artist/60IqCN3nOzZ13yd8dQy9cC'),
('Bruno Grasso', '4fNQqyvcM71IyF2EitEtCj', 'https://open.spotify.com/artist/4fNQqyvcM71IyF2EitEtCj'),
('Rapozt Mortem', '1KHXqOQxGsx47nQ3VsYCoy', 'https://open.spotify.com/artist/1KHXqOQxGsx47nQ3VsYCoy'),
('Justinani', '6daEHaxdKjnIGxdpeVRVMf', 'https://open.spotify.com/artist/6daEHaxdKjnIGxdpeVRVMf'),
('Malva', '1fKmFe01L78vPmmiJ10LAs', 'https://open.spotify.com/artist/1fKmFe01L78vPmmiJ10LAs'),
('Menuda Coincidencia', '6qmixZxMYL2jroxAqPQvRe', 'https://open.spotify.com/artist/6qmixZxMYL2jroxAqPQvRe'),
('La Banda Baston', '3vV4Tf1iC8vEP9fLOLGUfP', 'https://open.spotify.com/artist/3vV4Tf1iC8vEP9fLOLGUfP'),
('Spia 104', '49Q2I0njyI8l2nxCgXoGQ8', 'https://open.spotify.com/artist/49Q2I0njyI8l2nxCgXoGQ8'),
('Jauría Santa', '662f8mEv1eRLXE9DzBy4vV', 'https://open.spotify.com/artist/662f8mEv1eRLXE9DzBy4vV'),
('Solitario Mondragón', '4KXpp5lz2MakNFcTszi2B9', 'https://open.spotify.com/artist/4KXpp5lz2MakNFcTszi2B9'),
('Bipo Montana', '6JG2QQcaQBzinELNvu9PRk', 'https://open.spotify.com/artist/6JG2QQcaQBzinELNvu9PRk'),
('Caporal', '0lnkz75zUi8LVZeY8qd9tI', 'https://open.spotify.com/artist/0lnkz75zUi8LVZeY8qd9tI'),
('La Santa Grifa', '1oH2B8tcHn4Gpl2bmmyd4A', 'https://open.spotify.com/artist/1oH2B8tcHn4Gpl2bmmyd4A'),
('Playa Matafokas', '2xNpzwTQFG6D04SSTb32R1', 'https://open.spotify.com/artist/2xNpzwTQFG6D04SSTb32R1'),
('Stilo', '6nyqrmf9qc4W94YKtsPel9', 'https://open.spotify.com/artist/6nyqrmf9qc4W94YKtsPel9'),
('IQlover', '4f3gfMiBebyuTylgG4hHbq', 'https://open.spotify.com/artist/4f3gfMiBebyuTylgG4hHbq'),
('Poofer', '6KH83UCF9zwNaBi4IIJnjE', 'https://open.spotify.com/artist/6KH83UCF9zwNaBi4IIJnjE'),
('Jony Beltran', '7nN4ORhj5Mi3tgU9IwQrFv', 'https://open.spotify.com/artist/7nN4ORhj5Mi3tgU9IwQrFv'),
('Sipo one', '76V5aARZFI750zk1BglDV2', 'https://open.spotify.com/artist/76V5aARZFI750zk1BglDV2'),
('Kafe con leshe', '4UEgTTHyAS3pq9s4I7nhZj', 'https://open.spotify.com/artist/4UEgTTHyAS3pq9s4I7nhZj'),
('Seyer black', '0ajXUlyQnejinmO6xvBXtG', 'https://open.spotify.com/artist/0ajXUlyQnejinmO6xvBXtG'),
('Jezzy P', '2hRGPSlRUReuHtM0Cx0R7W', 'https://open.spotify.com/artist/2hRGPSlRUReuHtM0Cx0R7W'),
('Richard Aumada', '4oR06FdpsOJTcTnOkSzUsC', 'https://open.spotify.com/artist/4oR06FdpsOJTcTnOkSzUsC'),
('Kinto Sol', '0nOyxRsVicKeiBbB6zdIMu', 'https://open.spotify.com/artist/0nOyxRsVicKeiBbB6zdIMu'),
('Solo Cadaver', '2pOyR8sdYfEmd4VIyeLDUy', 'https://open.spotify.com/artist/2pOyR8sdYfEmd4VIyeLDUy'),
('Samantha Barron', '0zfvfy9XlborSqXNRhi8Bk', 'https://open.spotify.com/artist/0zfvfy9XlborSqXNRhi8Bk'),
('La Crista', '3yDz5xFKNHH0dE309ZN07K', 'https://open.spotify.com/artist/3yDz5xFKNHH0dE309ZN07K'),
('Prymanena', '3h0yqSdhPYKuC27VkPyYVh', 'https://open.spotify.com/artist/3h0yqSdhPYKuC27VkPyYVh'),
('Ayaari Nocedal', '5YEJGu6UlupM9I1E3T92rb', 'https://open.spotify.com/artist/5YEJGu6UlupM9I1E3T92rb'),
('Little Smoking', '5mFSaUUW9ZwqpWN39fmbuZ', 'https://open.spotify.com/artist/5mFSaUUW9ZwqpWN39fmbuZ'),
('Dely Underrap', '1jSge7y9Iuz9gd878P1MpH', 'https://open.spotify.com/artist/1jSge7y9Iuz9gd878P1MpH'),
('Barbarela', '2pFRwJDkZ3pvmzufOh2mc1', 'https://open.spotify.com/artist/2pFRwJDkZ3pvmzufOh2mc1'),
('Elie tigre', '6tM7AHGyfVc57FK5hZlEd1', 'https://open.spotify.com/artist/6tM7AHGyfVc57FK5hZlEd1'),
('Ogarita', '7F1M9d3MFyaMI7exRlfWsu', 'https://open.spotify.com/artist/7F1M9d3MFyaMI7exRlfWsu'),
('Under side', '2NtN73hhhgFt2NmbBOlFz1', 'https://open.spotify.com/artist/2NtN73hhhgFt2NmbBOlFz1'),
('Skilla OH', '2pDnTVieeXwx8R9HbyAjhP', 'https://open.spotify.com/artist/2pDnTVieeXwx8R9HbyAjhP'),
('Astrid Cruz', '1WhuV4MAbMhWKjYXojKN8i', 'https://open.spotify.com/artist/1WhuV4MAbMhWKjYXojKN8i'),
('Lady Yeska', '5wbGMxTkF76IVFgDjchC0J', 'https://open.spotify.com/artist/5wbGMxTkF76IVFgDjchC0J'),
('miss ganjah', '59DTprYmt2pwawfesGtjjH', 'https://open.spotify.com/artist/59DTprYmt2pwawfesGtjjH'),
('La gallo 320', '3vMfBXxAZ9iG2u0VjNZ0IA', 'https://open.spotify.com/artist/3vMfBXxAZ9iG2u0VjNZ0IA'),
('Nanis weed', '3E53XnrcqQ3FS7pxn20561', 'https://open.spotify.com/artist/3E53XnrcqQ3FS7pxn20561'),
('Bremont 420', '0Pm1HMMO0w5Suw6JY9zSlm', 'https://open.spotify.com/artist/0Pm1HMMO0w5Suw6JY9zSlm'),
('Dilema', '3eCEorgAoZkvnAQLdy4x38', 'https://open.spotify.com/artist/3eCEorgAoZkvnAQLdy4x38'),
('Netilico', '6olHsU1QdB0I5IBgVimUeU', 'https://open.spotify.com/artist/6olHsU1QdB0I5IBgVimUeU'),
('Tornillo', '5OGraDcSkO4oTWthkm77WL', 'https://open.spotify.com/artist/5OGraDcSkO4oTWthkm77WL'),
('Fiw', '5rQxUSIyxeFcOv6XY8cGcg', 'https://open.spotify.com/artist/5rQxUSIyxeFcOv6XY8cGcg'),
('King Zoo', '171953d8wJbRvl2f36uLDd', 'https://open.spotify.com/artist/171953d8wJbRvl2f36uLDd'),
('Elote el barbaro', '0yWcBatdQPfGvY4XEGeD6m', 'https://open.spotify.com/artist/0yWcBatdQPfGvY4XEGeD6m'),
('Sinful el pecador', '0CtBJEWIKkU8CzxJCBLmSi', 'https://open.spotify.com/artist/0CtBJEWIKkU8CzxJCBLmSi'),
('Chato 473', '7zvcqoLiInqmSmPzX0gwfp', 'https://open.spotify.com/artist/7zvcqoLiInqmSmPzX0gwfp'),
('Silar Kilos de estilo', '0EuMnBFVFmyIFFgpiwbvj6', 'https://open.spotify.com/artist/0EuMnBFVFmyIFFgpiwbvj6'),
('Dyablo', '7eU5CvFPPiqSqnKiNmZNy7', 'https://open.spotify.com/artist/7eU5CvFPPiqSqnKiNmZNy7'),
('Don kalavera', '2nJOVl8u7PntefIs1Uwb4z', 'https://open.spotify.com/artist/2nJOVl8u7PntefIs1Uwb4z'),
('Ñengo el quetzal', '6M7bd1arTLm5FJnNFYKzb6', 'https://open.spotify.com/artist/6M7bd1arTLm5FJnNFYKzb6'),
('Adan Zapata', '1NGy8h3j8jFQvFv6cniUnl', 'https://open.spotify.com/artist/1NGy8h3j8jFQvFv6cniUnl'),
('Lil wacho', '5LSBA1VYe9Vvxute4ZCaZQ', 'https://open.spotify.com/artist/5LSBA1VYe9Vvxute4ZCaZQ'),
('Sid MSC', '60ltkiwaQfISsFpwwktCcb', 'https://open.spotify.com/artist/60ltkiwaQfISsFpwwktCcb'),
('Jay Rick', '0U8dIwzBn17JkhYxmznp6T', 'https://open.spotify.com/artist/0U8dIwzBn17JkhYxmznp6T'),
('Sandro Malandro', '40FmJcZFhzbd6P9w4eXqgS', 'https://open.spotify.com/artist/40FmJcZFhzbd6P9w4eXqgS'),
('Illegalez', '1Fhcsda9LHOapGEZpOoAEj', 'https://open.spotify.com/artist/1Fhcsda9LHOapGEZpOoAEj'),
('High Life', '0VR2TEeHfqMZugZNANP1Dq', 'https://open.spotify.com/artist/0VR2TEeHfqMZugZNANP1Dq'),
('Mr Pimp music', '5zdoqaDKWhHtlFhoqfEn9N', 'https://open.spotify.com/artist/5zdoqaDKWhHtlFhoqfEn9N'),
('Maquina de fuego', '0cCaNgZOOoHOFP5z7NYXcJ', 'https://open.spotify.com/artist/0cCaNgZOOoHOFP5z7NYXcJ'),
('hombre Verso', '1eNa31nlPvphoLmNwUrIhM', 'https://open.spotify.com/artist/1eNa31nlPvphoLmNwUrIhM'),
('Pakal', '5ik5HDJQ996z6t41IBx6wu', 'https://open.spotify.com/artist/5ik5HDJQ996z6t41IBx6wu'),
('Alan SDR', '4WHwVAuDtEVKIREviMhYOB', 'https://open.spotify.com/artist/4WHwVAuDtEVKIREviMhYOB'),
('Cristy Loza', '3Fz6oCeasrR52Sv7NJfpml', 'https://open.spotify.com/artist/3Fz6oCeasrR52Sv7NJfpml'),
('Hione', '0F3owIAAiwFiIzGP2YU6mg', 'https://open.spotify.com/artist/0F3owIAAiwFiIzGP2YU6mg');

INSERT INTO youtube_artist_channels (artist_name, youtube_channel_id, channel_url) VALUES
('Aleman', 'UC9qH_PzG3TpfJpsRt9VfKcA', 'https://www.youtube.com/channel/UC9qH_PzG3TpfJpsRt9VfKcA'),
('Neto Peña', 'UCrq2ArYU6XzMg_uAVPHCE3Q', 'https://www.youtube.com/channel/UCrq2ArYU6XzMg_uAVPHCE3Q'),
('Santa Fe Klan', 'UC4Ge3cqrdyOszmnJTcMICcg', 'https://www.youtube.com/channel/UC4Ge3cqrdyOszmnJTcMICcg'),
('Metrik Vader', 'UCOmtNKVF6BM8uNDbJR6D4LQ', 'https://www.youtube.com/channel/UCOmtNKVF6BM8uNDbJR6D4LQ'),
('CKAN', 'UCkD89TEFWsTZluY6tk84yqg', 'https://www.youtube.com/channel/UCkD89TEFWsTZluY6tk84yqg'),
('LNGSHT', 'UCwjXCWlTgAhfBlqttfFZ5rw', 'https://www.youtube.com/channel/UCwjXCWlTgAhfBlqttfFZ5rw'),
('AdanCruz', 'UCsNud7A3Vz8X8Pqfw2L2wKg', 'https://www.youtube.com/channel/UCsNud7A3Vz8X8Pqfw2L2wKg'),
('Sr Marrano', 'UC1jqOSFKURb0QR9yErkBHlQ', 'https://www.youtube.com/channel/UC1jqOSFKURb0QR9yErkBHlQ'),
('THRCru2', 'UCXCiZmPpHnrAQ1mcfKQYm2A', 'https://www.youtube.com/channel/UCXCiZmPpHnrAQ1mcfKQYm2A'),
('EptosUno', 'UCsjwZJsy9IiykfPbZmYvp1A', 'https://www.youtube.com/channel/UCsjwZJsy9IiykfPbZmYvp1A'),
('Mime 871', 'UCcOlDiuXhTuNZlAZOmm21tA', 'https://www.youtube.com/channel/UCcOlDiuXhTuNZlAZOmm21tA'),
('Pato Machete', 'UCNVcXV-xZsnHjVxYSMEZROQ', 'https://www.youtube.com/channel/UCNVcXV-xZsnHjVxYSMEZROQ'),
('Control Machete', 'UC9IzX1jMwTETgdV4WIIEvmQ', 'https://www.youtube.com/channel/UC9IzX1jMwTETgdV4WIIEvmQ'),
('Tino El Pinguino', 'UCvkIHNuCuQs-JWF12f9TFvA', 'https://www.youtube.com/channel/UCvkIHNuCuQs-JWF12f9TFvA'),
('Boca Floja', 'UCACalOr4wnNpTWw9Yyet4Tw', 'https://www.youtube.com/channel/UCACalOr4wnNpTWw9Yyet4Tw'),
('Akil Ammar', 'UCmNYsUc6ce4rH-GRFblKbCA', 'https://www.youtube.com/channel/UCmNYsUc6ce4rH-GRFblKbCA'),
('West Gold', 'UCvWNSFSHsGhaVXbJI_W3cdw', 'https://www.youtube.com/channel/UCvWNSFSHsGhaVXbJI_W3cdw'),
('Robot', 'UCliRD7DSeqcuzudajJdWaLg', 'https://www.youtube.com/channel/UCliRD7DSeqcuzudajJdWaLg'),
('king zoo', 'UCl7BaSud7ML0WNowcsBFQ8w', 'https://www.youtube.com/channel/UCl7BaSud7ML0WNowcsBFQ8w'),
('Dharius', 'UCRWeaLWbhoHuHNjxLgG4asQ', 'https://www.youtube.com/channel/UCRWeaLWbhoHuHNjxLgG4asQ'),
('Hispana', 'UC41ykKNl4Kakh6ISHp0KpVg', 'https://www.youtube.com/channel/UC41ykKNl4Kakh6ISHp0KpVg'),
('Cartel de Santa', 'UCunw-c0EKIX5LpPo8GpA2Aw', 'https://www.youtube.com/channel/UCunw-c0EKIX5LpPo8GpA2Aw'),
('Aczino', 'UCGbyLk1twkkSSCFFMP1AZ9A', 'https://www.youtube.com/channel/UCGbyLk1twkkSSCFFMP1AZ9A'),
('Coko', 'UC_qoGP7DFmu4JPLnF93tafQ', 'https://www.youtube.com/channel/UC_qoGP7DFmu4JPLnF93tafQ'),
('Charles Ans', 'UCVg8JuO9t0ZAmzPcd7C6AIQ', 'https://www.youtube.com/channel/UCVg8JuO9t0ZAmzPcd7C6AIQ'),
('Gera Mx', 'UCwEJBGLB1knx2pYESEvWDWg', 'https://www.youtube.com/channel/UCwEJBGLB1knx2pYESEvWDWg'),
('Yoss Bones', 'UCeQMZ68wcb97NCCKiI2KxnQ', 'https://www.youtube.com/channel/UCeQMZ68wcb97NCCKiI2KxnQ'),
('Tabernario', 'UCXrtY_gHYMsPymMri6jRcsA', 'https://www.youtube.com/channel/UCXrtY_gHYMsPymMri6jRcsA'),
('WK', 'UCLDG3G9RkdwDhrqxECJcTGQ', 'https://www.youtube.com/channel/UCLDG3G9RkdwDhrqxECJcTGQ'),
('Mike Diaz', 'UCUg3gPjQk3MqMd3jKRbt4pA', 'https://www.youtube.com/channel/UCUg3gPjQk3MqMd3jKRbt4pA'),
('Lefty SM', 'UCQFmPWnstWJ5LMwRmsK34Vg', 'https://www.youtube.com/channel/UCQFmPWnstWJ5LMwRmsK34Vg'),
('T-Killa', 'UC9o3zPDOe3gLomzwdKXFnog', 'https://www.youtube.com/channel/UC9o3zPDOe3gLomzwdKXFnog'),
('Faruz Feet', 'UCyVy4S_1se6l-8u14eSMalg', 'https://www.youtube.com/channel/UCyVy4S_1se6l-8u14eSMalg'),
('Spvce Problems', 'UCiXdgdYslSIrz3PbC-7JiNg', 'https://www.youtube.com/channel/UCiXdgdYslSIrz3PbC-7JiNg'),
('Reno 871', 'UCzinKCm3KrqoAiJGgToNzpw', 'https://www.youtube.com/channel/UCzinKCm3KrqoAiJGgToNzpw'),
('Big Metra', 'UCW_8p4Mi94UQg7vQPRwrGKA', 'https://www.youtube.com/channel/UCW_8p4Mi94UQg7vQPRwrGKA'),
('Achepe', 'UCfTcSqx_3gSHtThZDg73Low', 'https://www.youtube.com/channel/UCfTcSqx_3gSHtThZDg73Low'),
('Santa RM', 'UCwiiACQ5jBDLF1kbrdzVaWA', 'https://www.youtube.com/channel/UCwiiACQ5jBDLF1kbrdzVaWA'),
('Fntxy', 'UCd3rXLucYUfOe4I0cPo6GqQ', 'https://www.youtube.com/channel/UCd3rXLucYUfOe4I0cPo6GqQ'),
('Yoga Fire', 'UCKW16mhYlN53-pfwWt3XJvQ', 'https://www.youtube.com/channel/UCKW16mhYlN53-pfwWt3XJvQ'),
('Anexo Leiruk', 'UCdV9NxSCAhc1jUPBlrwhOdQ', 'https://www.youtube.com/channel/UCdV9NxSCAhc1jUPBlrwhOdQ'),
('Millonario', 'UC35vyo1h2K_jLNi8oFtC9QA', 'https://www.youtube.com/channel/UC35vyo1h2K_jLNi8oFtC9QA'),
('Tren Lokote', 'UCP5-WPv_aHthE2jTZoLHbmg', 'https://www.youtube.com/channel/UCP5-WPv_aHthE2jTZoLHbmg'),
('El Pinche Mara', 'UCCj3pPQEgk_AMvWi5_1RYHw', 'https://www.youtube.com/channel/UCCj3pPQEgk_AMvWi5_1RYHw'),
('Geassasin', 'UCC8gEoiVZcB24IIOBQfmpyQ', 'https://www.youtube.com/channel/UCC8gEoiVZcB24IIOBQfmpyQ'),
('Logan Hate', 'UC7prW0Eq54-nv1d9j99l8qQ', 'https://www.youtube.com/channel/UC7prW0Eq54-nv1d9j99l8qQ'),
('Dracks', 'UCwMgQFIKrh6xyszppvRHhZw', 'https://www.youtube.com/channel/UCwMgQFIKrh6xyszppvRHhZw'),
('Phyz Eye', 'UCzPWzNmROkktq4YRFg2y0MQ', 'https://www.youtube.com/channel/UCzPWzNmROkktq4YRFg2y0MQ'),
('Zaque', 'UCXLJPF4RRLT4aoVJkXG80bg', 'https://www.youtube.com/channel/UCXLJPF4RRLT4aoVJkXG80bg'),
('Muthahupa', 'UCxHKmJE_c5IimjhQdksRYoA', 'https://www.youtube.com/channel/UCxHKmJE_c5IimjhQdksRYoA'),
('Teeam Revolver', 'UCh0EgbExTBNiB31bjhfht_Q', 'https://www.youtube.com/channel/UCh0EgbExTBNiB31bjhfht_Q'),
('Tiro Loko', 'UCjvALbPcnSIS1xRjSvB7WCg', 'https://www.youtube.com/channel/UCjvALbPcnSIS1xRjSvB7WCg'),
('Simspon ahuevo', 'UCC42KGg_brOsjfA8ABAN5xQ', 'https://www.youtube.com/channel/UCC42KGg_brOsjfA8ABAN5xQ'),
('Go Golden Junk', 'UCO0cFgu4mVmCmmg9coTJDlg', 'https://www.youtube.com/channel/UCO0cFgu4mVmCmmg9coTJDlg'),
('Primero company', 'UCn2GwyJIIFKcxINfpp5TmxQ', 'https://www.youtube.com/channel/UCn2GwyJIIFKcxINfpp5TmxQ'),
('Tanke one', 'UCjqSpoNRtIoeZeDUjvDaGmg', 'https://www.youtube.com/channel/UCjqSpoNRtIoeZeDUjvDaGmg'),
('Gino', 'UCJ0qtr3XpTk5v0_eDgeLqEQ', 'https://www.youtube.com/channel/UCJ0qtr3XpTk5v0_eDgeLqEQ'),
('Montebel', 'UCPcnyvY1XIC57mUnJzZSx1Q', 'https://www.youtube.com/channel/UCPcnyvY1XIC57mUnJzZSx1Q'),
('Proof', 'UCkXBIPhqndAH5vqgMJyIZeg', 'https://www.youtube.com/channel/UCkXBIPhqndAH5vqgMJyIZeg'),
('Hadrian', 'UCDN7z4dol0uUHf749gJrrvQ', 'https://www.youtube.com/channel/UCDN7z4dol0uUHf749gJrrvQ'),
('El pinche brujo', 'UC8qBl25vUefhuklVQLx7cJQ', 'https://www.youtube.com/channel/UC8qBl25vUefhuklVQLx7cJQ'),
('Bull Montana', 'UCY0SVFoEwcsLfKs7LXUsXNQ', 'https://www.youtube.com/channel/UCY0SVFoEwcsLfKs7LXUsXNQ'),
('Tonnie Rico', 'UCFh6L1uNQj1n-T--ARecANA', 'https://www.youtube.com/channel/UCFh6L1uNQj1n-T--ARecANA'),
('Dasket Rapley', 'UC1M0jJqDr4eOYXQJ1ZvnV6g', 'https://www.youtube.com/channel/UC1M0jJqDr4eOYXQJ1ZvnV6g'),
('Little el Crack', 'UCU2tjq7ZmZhIfwkdtikAW8Q', 'https://www.youtube.com/channel/UCU2tjq7ZmZhIfwkdtikAW8Q'),
('Leazzy', 'UCmcMLtd_OaX_-GG8GIUgqew', 'https://www.youtube.com/channel/UCmcMLtd_OaX_-GG8GIUgqew'),
('Rabia Rivera', 'UCFDrkf0_avZvZ9NJdPWwKkg', 'https://www.youtube.com/channel/UCFDrkf0_avZvZ9NJdPWwKkg'),
('Sociedad Cafe', 'UCEHcjPXK3ghcIwZ2sflg5LA', 'https://www.youtube.com/channel/UCEHcjPXK3ghcIwZ2sflg5LA'),
('Turek Hem', 'UCx7FMYdnthMR7FouYrfJ0fQ', 'https://www.youtube.com/channel/UCx7FMYdnthMR7FouYrfJ0fQ'),
('Jay Romero', 'UCG_LojB0IUo8vi1xcyIJrXg', 'https://www.youtube.com/channel/UCG_LojB0IUo8vi1xcyIJrXg'),
('Remik', 'UC1hlr4QMZoNPEuxXOvsFhqA', 'https://www.youtube.com/channel/UC1hlr4QMZoNPEuxXOvsFhqA'),
('Toser One', 'UCQf542MPMWUWq6l65rsV_Kw', 'https://www.youtube.com/channel/UCQf542MPMWUWq6l65rsV_Kw'),
('Under Side', 'UC65j313QwkFbx6fwGo4Oh5w', 'https://www.youtube.com/channel/UC65j313QwkFbx6fwGo4Oh5w'),
('Mc Davo', 'UCCmXcYtA4T9wxc3vmbGFxRA', 'https://www.youtube.com/channel/UCCmXcYtA4T9wxc3vmbGFxRA'),
('Neto Reyno', 'UCGo_5Z7bBN53zAXCXHGYYBg', 'https://www.youtube.com/channel/UCGo_5Z7bBN53zAXCXHGYYBg'),
('Snow tha product', 'UCb934vQ6fg1JZQKvkCQ_j-Q', 'https://www.youtube.com/channel/UCb934vQ6fg1JZQKvkCQ_j-Q'),
('Ximbo', 'UCBcbw1KWVa6I30snV6Eovpg', 'https://www.youtube.com/channel/UCBcbw1KWVa6I30snV6Eovpg'),
('Vikcy MC', 'UC1n9krq-c4QS54Ongn321zg', 'https://www.youtube.com/channel/UC1n9krq-c4QS54Ongn321zg'),
('Zimple', 'UCGTvaChL1QKtfjyTGSAmTfQ', 'https://www.youtube.com/channel/UCGTvaChL1QKtfjyTGSAmTfQ'),
('Zxmyr', 'UCZ4NWZseJmo7QXlZKkib_iA', 'https://www.youtube.com/channel/UCZ4NWZseJmo7QXlZKkib_iA'),
('Lenin Pena', 'UCOwUHROBsFWiMjO5n_TvxpQ', 'https://www.youtube.com/channel/UCOwUHROBsFWiMjO5n_TvxpQ'),
('Smoky', 'UCc4Ynwucqf4PRdFSP2zhUFA', 'https://www.youtube.com/channel/UCc4Ynwucqf4PRdFSP2zhUFA'),
('Guero Sosa', 'UCGH05t7k8We4RtCP78ahxZg', 'https://www.youtube.com/channel/UCGH05t7k8We4RtCP78ahxZg'),
('Maythugs', 'UCPgrJbHM_xj_VTlkGgazm_Q', 'https://www.youtube.com/channel/UCPgrJbHM_xj_VTlkGgazm_Q'),
('Lirika Inverza', 'UC5ZfH3CHGSiwfYg0u2pCDZQ', 'https://www.youtube.com/channel/UC5ZfH3CHGSiwfYg0u2pCDZQ'),
('Bizor', 'UCHPiQ86JdN3FILNDwR_mxkw', 'https://www.youtube.com/channel/UCHPiQ86JdN3FILNDwR_mxkw'),
('Caballeros del plan g', 'UCUFzwKTcTQkEyMYdND7NNfQ', 'https://www.youtube.com/channel/UCUFzwKTcTQkEyMYdND7NNfQ'),
('Don Aereo', 'UCaEZ1OAjebcZOnVcNhBZrZQ', 'https://www.youtube.com/channel/UCaEZ1OAjebcZOnVcNhBZrZQ'),
('Kosmer', 'UCFmQe7QD6vNG0761Vb-lTGg', 'https://www.youtube.com/channel/UCFmQe7QD6vNG0761Vb-lTGg'),
('Doctor Destino', 'UCGXC-OtIZ7PHOHBKZTE4mIw', 'https://www.youtube.com/channel/UCGXC-OtIZ7PHOHBKZTE4mIw'),
('Danger Ak', 'UCRma-nTsuq_4w9KkCJJYSig', 'https://www.youtube.com/channel/UCRma-nTsuq_4w9KkCJJYSig'),
('Cozy Cuz', 'UChyHg_8LNYa3yydCNcfp5ZQ', 'https://www.youtube.com/channel/UChyHg_8LNYa3yydCNcfp5ZQ'),
('Maniako', 'UCBAabiLiKLsB6uhKuTdRa0g', 'https://www.youtube.com/channel/UCBAabiLiKLsB6uhKuTdRa0g'),
('Kstro MGA', 'UCxtFOI2k-NwJpy8Qv4dDH6w', 'https://www.youtube.com/channel/UCxtFOI2k-NwJpy8Qv4dDH6w'),
('Cesaranderan', 'UCb0kJUplVTwAs20FvSAX11A', 'https://www.youtube.com/channel/UCb0kJUplVTwAs20FvSAX11A'),
('Perro ZW', 'UC9PJj_Wj2XK_6Cd8YwAVbnQ', 'https://www.youtube.com/channel/UC9PJj_Wj2XK_6Cd8YwAVbnQ'),
('Nedman Guerrero', 'UCQ51rJk17ryq0bQOqxwC3_w', 'https://www.youtube.com/channel/UCQ51rJk17ryq0bQOqxwC3_w'),
('Rhomer', 'UC8yPdJQF5GMbf7phZixqc7Q', 'https://www.youtube.com/channel/UC8yPdJQF5GMbf7phZixqc7Q'),
('Kidd M', 'UCSBtOiP93gtOKBUxzH82cdA', 'https://www.youtube.com/channel/UCSBtOiP93gtOKBUxzH82cdA'),
('Mc Luka', 'UCtA_PL0vHPlJdJWG1U5wrtA', 'https://www.youtube.com/channel/UCtA_PL0vHPlJdJWG1U5wrtA'),
('Skool 77', 'UCTpJ5FCcMwtlKaGPM3KmtXg', 'https://www.youtube.com/channel/UCTpJ5FCcMwtlKaGPM3KmtXg'),
('Fermin IV', 'UCGM3UlzIWwkQipcweaNaiYA', 'https://www.youtube.com/channel/UCGM3UlzIWwkQipcweaNaiYA'),
('Gogo Ras', 'UCl8RpiWbO_usXsUVcCt65Tw', 'https://www.youtube.com/channel/UCl8RpiWbO_usXsUVcCt65Tw'),
('Dee', 'UCEGMF-OtAZZFZmKNovSIdGg', 'https://www.youtube.com/channel/UCEGMF-OtAZZFZmKNovSIdGg'),
('Industria City', 'UC_IjyhW-bNkMyTl67trAPHg', 'https://www.youtube.com/channel/UC_IjyhW-bNkMyTl67trAPHg'),
('Gooti Records', 'UCtMv-a8SY-rO7KBg9hgaWMQ', 'https://www.youtube.com/channel/UCtMv-a8SY-rO7KBg9hgaWMQ'),
('Masta Quba', 'UCT_pGv1vC2W9FxSF4d1ARYw', 'https://www.youtube.com/channel/UCT_pGv1vC2W9FxSF4d1ARYw'),
('Audry Funk', 'UCP0bHEgMjKkbvHLJPO3Pgvg', 'https://www.youtube.com/channel/UCP0bHEgMjKkbvHLJPO3Pgvg'),
('Ogarita', 'UC9MfCD9NvAuUcc3-SdtnSZQ', 'https://www.youtube.com/channel/UC9MfCD9NvAuUcc3-SdtnSZQ'),
('Ballin', 'UC-Un35k-4kAVt_ZayveoHDQ', 'https://www.youtube.com/channel/UC-Un35k-4kAVt_ZayveoHDQ'),
('Escuela Sinica', 'UC8QPOUi9Al6vjtzJUTU4AqQ', 'https://www.youtube.com/channel/UC8QPOUi9Al6vjtzJUTU4AqQ'),
('Mare Advertencia Lirika', 'UCoeKgIyB_k2HU_Wd0nyCcAA', 'https://www.youtube.com/channel/UCoeKgIyB_k2HU_Wd0nyCcAA'),
('Bobi Bozman', 'UCwxsBHYjR-26lqb4rumBQfg', 'https://www.youtube.com/channel/UCwxsBHYjR-26lqb4rumBQfg'),
('Fume 871', 'UCIsL3HP_ub3RJL357hge9vA', 'https://www.youtube.com/channel/UCIsL3HP_ub3RJL357hge9vA'),
('Drvgs', 'UCbqWnvHkYPlw6QhMIun8p8w', 'https://www.youtube.com/channel/UCbqWnvHkYPlw6QhMIun8p8w'),
('Limbo Lowfi', 'UCV0NSwIfpiI8UM9oclyAT7A', 'https://www.youtube.com/channel/UCV0NSwIfpiI8UM9oclyAT7A'),
('Doble P Ache Ene', 'UCKTOXzyK8A949bkGLL_s-yg', 'https://www.youtube.com/channel/UCKTOXzyK8A949bkGLL_s-yg'),
('Rhinox', 'UCCgru39nvvT4HagCeAzF7cg', 'https://www.youtube.com/channel/UCCgru39nvvT4HagCeAzF7cg'),
('Carlos Cartoon', 'UCHmPzq-rblI2ePxWGkiqr_Q', 'https://www.youtube.com/channel/UCHmPzq-rblI2ePxWGkiqr_Q'),
('Eric El Niño', 'UCYK6niNrGz_a0r95tjalt-w', 'https://www.youtube.com/channel/UCYK6niNrGz_a0r95tjalt-w');

INSERT INTO youtube_artist_channels (artist_name, youtube_channel_id, channel_url) VALUES
('Yak MAg', 'UC3HDL48GvKcsItnMWMmAf3Q', 'https://www.youtube.com/channel/UC3HDL48GvKcsItnMWMmAf3Q'),
('Rapozt Mortem', 'UCtzRQlSROUqceyhsyt-yZRw', 'https://www.youtube.com/channel/UCtzRQlSROUqceyhsyt-yZRw'),
('Justinani', 'UCWx6wb45qiquiSOVo9n_jFQ', 'https://www.youtube.com/channel/UCWx6wb45qiquiSOVo9n_jFQ'),
('Menuda Coincidencia', 'UCk6kHu64yemOY3rhoYNwndw', 'https://www.youtube.com/channel/UCk6kHu64yemOY3rhoYNwndw'),
('La Banda Baston', 'UCHNAy303XjuHFutICph-xyQ', 'https://www.youtube.com/channel/UCHNAy303XjuHFutICph-xyQ'),
('Jauría Santa', 'UCAoiYfsSUrfKzNqmYSe3sbA', 'https://www.youtube.com/channel/UCAoiYfsSUrfKzNqmYSe3sbA'),
('Solitario Mondragón', 'UC6aHJnbrit1oPsyJl_S1zew', 'https://www.youtube.com/channel/UC6aHJnbrit1oPsyJl_S1zew'),
('Bipo Montana', 'UCozby0zIOZuLVVRKg9Yk7KQ', 'https://www.youtube.com/channel/UCozby0zIOZuLVVRKg9Yk7KQ'),
('Caporal', 'UCfcpt5PTNAACwcnJUbrj6hA', 'https://www.youtube.com/channel/UCfcpt5PTNAACwcnJUbrj6hA'),
('La Santa Grifa', 'UCOHiOs8GrK0Nz8p_fbNnADQ', 'https://www.youtube.com/channel/UCOHiOs8GrK0Nz8p_fbNnADQ'),
('Stilo', 'UCaeB4QDRK-lI2Afif8j3oUg', 'https://www.youtube.com/channel/UCaeB4QDRK-lI2Afif8j3oUg'),
('Poofer', 'UC1xVjSVgk5YXpAK8db1JyWA', 'https://www.youtube.com/channel/UC1xVjSVgk5YXpAK8db1JyWA'),
('Jony Beltran', 'UCvMG8jdxTfTfZTMOtN7BG6g', 'https://www.youtube.com/channel/UCvMG8jdxTfTfZTMOtN7BG6g'),
('Sipo one', 'UC_DHJfesxbCEmg9b_AJRNcA', 'https://www.youtube.com/channel/UC_DHJfesxbCEmg9b_AJRNcA'),
('Kafe con leshe', 'UCMZDsInSio5ELUZaiyWmTLg', 'https://www.youtube.com/channel/UCMZDsInSio5ELUZaiyWmTLg'),
('Jezzy P', 'UC99BrDRiPkPURkDkhJPxgZA', 'https://www.youtube.com/channel/UC99BrDRiPkPURkDkhJPxgZA'),
('Richard Aumada', 'UCDlgDrcAcfDgA7EOfwi_L4w', 'https://www.youtube.com/channel/UCDlgDrcAcfDgA7EOfwi_L4w'),
('Kinto Sol', 'UC89T-BR3lxaq89mqx6qPGfA', 'https://www.youtube.com/channel/UC89T-BR3lxaq89mqx6qPGfA'),
('Fosa Comun', 'UCM67oH4uzA7kWxh7Pf4G37w', 'https://www.youtube.com/channel/UCM67oH4uzA7kWxh7Pf4G37w'),
('skilla holiday', 'UCjGczgZ8eeUj8zEWhcrSnyw', 'https://www.youtube.com/channel/UCjGczgZ8eeUj8zEWhcrSnyw'),
('dabeat ramirez', 'UCtpFK8OKRazxx8f46ZeGPNQ', 'https://www.youtube.com/channel/UCtpFK8OKRazxx8f46ZeGPNQ'),
('seyer black', 'UCaMofUsHxRr3AjN-WlLPUrQ', 'https://www.youtube.com/channel/UCaMofUsHxRr3AjN-WlLPUrQ'),
('solo cadaver', 'UCaoaWmbKyrzkjNpPKO-elhQ', 'https://www.youtube.com/channel/UCaoaWmbKyrzkjNpPKO-elhQ'),
('fiw', 'UCWPUInlefYIPxfD4FuKfNfA', 'https://www.youtube.com/channel/UCWPUInlefYIPxfD4FuKfNfA'),
('la gallo', 'UCk-iNn1I0SzbI6OuCNMxtrg', 'https://www.youtube.com/channel/UCk-iNn1I0SzbI6OuCNMxtrg'),
('barbarela', 'UCNPDNMpvHLh9UNWcTVj9Y5Q', 'https://www.youtube.com/channel/UCNPDNMpvHLh9UNWcTVj9Y5Q'),
('gisela gaxiola', 'UCH6sYgwQ68hi9pFL-kZ6vZA', 'https://www.youtube.com/channel/UCH6sYgwQ68hi9pFL-kZ6vZA'),
('samantha barron', 'UC26ng48UilLq6eEpahHufmQ', 'https://www.youtube.com/channel/UC26ng48UilLq6eEpahHufmQ'),
('astrid cruz', 'UC2gMOMJbxMeT0ncLGSvPLNQ', 'https://www.youtube.com/channel/UC2gMOMJbxMeT0ncLGSvPLNQ'),
('lorena padme', 'UC5WbdC53ULuI8lDeQZkLLfA', 'https://www.youtube.com/channel/UC5WbdC53ULuI8lDeQZkLLfA'),
('neftys', 'UCNBluHIJvLb41CZHm5UU0qg', 'https://www.youtube.com/channel/UCNBluHIJvLb41CZHm5UU0qg'),
('tu segunda madre', 'UCZGrmyeQSq_0CZo8YKQAjog', 'https://www.youtube.com/channel/UCZGrmyeQSq_0CZo8YKQAjog'),
('elie tigre', 'UC70gIpZPu9EUqT4OypyYI-Q', 'https://www.youtube.com/channel/UC70gIpZPu9EUqT4OypyYI-Q'),
('Yeimy Ochoa', 'UCB4Ppj1MwBGI9Ef4UKqJ1wQ', 'https://www.youtube.com/channel/UCB4Ppj1MwBGI9Ef4UKqJ1wQ'),
('Ayaari nocedal', 'UCMoW-JmJdy3th3Lj6MLgxZg', 'https://www.youtube.com/channel/UCMoW-JmJdy3th3Lj6MLgxZg'),
('Prima nena', 'UCAk71VHs-2cwRBk8r61tbQA', 'https://www.youtube.com/channel/UCAk71VHs-2cwRBk8r61tbQA'),
('Nanis weed', 'UCrwSa_k0p7N7vHrL-CIypkg', 'https://www.youtube.com/channel/UCrwSa_k0p7N7vHrL-CIypkg'),
('Picky Ramirez', 'UCRKNvroYfaEV580dwS8zGJQ', 'https://www.youtube.com/channel/UCRKNvroYfaEV580dwS8zGJQ'),
('Dely Underrap', 'UCmc4PSq3005xCQxTh470Brg', 'https://www.youtube.com/channel/UCmc4PSq3005xCQxTh470Brg'),
('Jota ache', 'UCJIAvcZzpi2b-1yphqbdRDw', 'https://www.youtube.com/channel/UCJIAvcZzpi2b-1yphqbdRDw'),
('Hechura', 'UCANIkUXgxwaKBqas2jTEoAg', 'https://www.youtube.com/channel/UCANIkUXgxwaKBqas2jTEoAg'),
('Abril Mancilla', 'UC7a6heE-U0M9vMtKk_-4b8Q', 'https://www.youtube.com/channel/UC7a6heE-U0M9vMtKk_-4b8Q'),
('Miss Ganjah', 'UCXp-STMrAEWPYnlvHEiC9qg', 'https://www.youtube.com/channel/UCXp-STMrAEWPYnlvHEiC9qg'),
('Ana mc', 'UC46IXCPX-vp0zlgiivNWfZA', 'https://www.youtube.com/channel/UC46IXCPX-vp0zlgiivNWfZA'),
('Ikal Killa', 'UCn9h9dp04vghq2ECpjI8X3Q', 'https://www.youtube.com/channel/UCn9h9dp04vghq2ECpjI8X3Q'),
('Little Smoking', 'UCEJFz7QINlpcUoeYGUAvVDA', 'https://www.youtube.com/channel/UCEJFz7QINlpcUoeYGUAvVDA'),
('La Gyal', 'UCfIAcQ5pnHrBjsu4S0YJuCA', 'https://www.youtube.com/channel/UCfIAcQ5pnHrBjsu4S0YJuCA');

-- Incremento sugerido desde la API (fuera de /admin, status < 400):
-- INSERT INTO endpoint_counter (endpoint_path, success_count, last_success_at)
-- VALUES (:path, 1, UTC_TIMESTAMP())
-- ON DUPLICATE KEY UPDATE success_count = success_count + 1, last_success_at = UTC_TIMESTAMP();
